'use strict';
const ASSET_BACKUP_ENV=typeof APP_ENV==='string'?APP_ENV:(typeof QA_MODE!=='undefined'&&QA_MODE?'qa':'live'),ASSET_BACKUP_DB=`asset-os-backup-v05-${ASSET_BACKUP_ENV}`,ASSET_BACKUP_STORE='handles',ASSET_PHONE_HANDLE_KEY=`phone-directory-${ASSET_BACKUP_ENV}`,ASSET_DAILY_KEEP_DAYS=30,ASSET_AUTO_BACKUP_DELAY=60000;
let assetAutoBackupTimer=0,assetBackupWriting=false;
function assetBackupSettings(){const base={phoneEnabled:false,lastPhoneBackupAt:'',lastReleaseVersion:'',phonePermission:'unknown'},current=state.settings.backupV04&&typeof state.settings.backupV04==='object'?state.settings.backupV04:(state.settings.backupV04={});for(const [key,value] of Object.entries(base))if(current[key]===undefined)current[key]=value;return current}
function assetBackupDateCode(date=new Date()){return `${String(date.getFullYear()).slice(-2)}${String(date.getMonth()+1).padStart(2,'0')}${String(date.getDate()).padStart(2,'0')}`}
function assetBackupSafeVersion(version=APP_VERSION){return String(version||APP_VERSION).replace(/[^0-9A-Za-z._-]/g,'')||APP_VERSION}
function assetManagedBackupName({date=new Date(),version=APP_VERSION,tag=''}={}){return `AssetOS_${ASSET_BACKUP_ENV==='qa'?'QA_':''}${assetBackupDateCode(date)}_${assetBackupSafeVersion(version)}${tag?`_${tag}`:''}.zip`}
function assetOpenBackupDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(ASSET_BACKUP_DB,1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(ASSET_BACKUP_STORE))request.result.createObjectStore(ASSET_BACKUP_STORE)};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||new Error('백업 폴더 저장소를 열지 못했습니다.'))})}
async function assetBackupHandleGet(){const db=await assetOpenBackupDb();try{return await new Promise((resolve,reject)=>{const tx=db.transaction(ASSET_BACKUP_STORE,'readonly'),request=tx.objectStore(ASSET_BACKUP_STORE).get(ASSET_PHONE_HANDLE_KEY);request.onsuccess=()=>resolve(request.result||null);request.onerror=()=>reject(request.error)})}finally{db.close()}}
async function assetBackupHandleSet(handle){const db=await assetOpenBackupDb();try{await new Promise((resolve,reject)=>{const tx=db.transaction(ASSET_BACKUP_STORE,'readwrite');tx.objectStore(ASSET_BACKUP_STORE).put(handle,ASSET_PHONE_HANDLE_KEY);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}finally{db.close()}}
async function assetBackupPermission(handle,request=false){if(!handle)return'denied';const options={mode:'readwrite'};if(typeof handle.queryPermission==='function'){const value=await handle.queryPermission(options);if(value==='granted'||!request)return value}if(request&&typeof handle.requestPermission==='function')return handle.requestPermission(options);return'prompt'}
async function assetPhoneBackupHandle(request=false){try{const handle=await assetBackupHandleGet();if(!handle)return null;const permission=await assetBackupPermission(handle,request);assetBackupSettings().phonePermission=permission;return permission==='granted'?handle:null}catch{return null}}
function assetParseManagedBackup(name){const match=/^AssetOS_(QA_)?(\d{6})_(v[0-9A-Za-z._-]+?)(?:_(pre|keep))?\.zip$/i.exec(String(name||''));if(!match)return null;const environment=match[1]?'qa':'live',year=2000+Number(match[2].slice(0,2)),month=Number(match[2].slice(2,4)),day=Number(match[2].slice(4,6)),date=new Date(year,month-1,day);if(date.getFullYear()!==year||date.getMonth()!==month-1||date.getDate()!==day)return null;return{date,month:`${year}-${String(month).padStart(2,'0')}`,tag:match[4]||'',environment}}
function assetBackupRetentionPlan(rows,now=new Date()){const cutoff=new Date(now.getFullYear(),now.getMonth(),now.getDate()-ASSET_DAILY_KEEP_DAYS),keep=new Set(),old=[];for(const row of rows){if(row.info.tag||row.info.date>=cutoff)keep.add(row.name);else old.push(row)}const monthly=new Map();for(const row of old){const current=monthly.get(row.info.month);if(!current||current.info.date<row.info.date)monthly.set(row.info.month,row)}for(const row of monthly.values())keep.add(row.name);return{keep,remove:rows.filter(row=>!keep.has(row.name)).map(row=>row.name)}}
async function assetCleanupPhoneBackups(handle){const rows=[];for await(const [name,entry] of handle.entries())if(entry.kind==='file'){const info=assetParseManagedBackup(name);if(info&&info.environment===ASSET_BACKUP_ENV)rows.push({name,info})}const plan=assetBackupRetentionPlan(rows);for(const name of plan.remove)await handle.removeEntry(name);return plan}
async function assetWritePhoneBackup({tag='',version=APP_VERSION,silent=false}={}){if(assetBackupWriting)return false;const handle=await assetPhoneBackupHandle(false);if(!handle){if(!silent)showNotice('휴대폰 백업 폴더 연결이 필요합니다.','백업·복원에서 폴더를 한 번 지정해 주세요. 지원하지 않는 브라우저에서는 ZIP 다운로드를 사용합니다.');return false}assetBackupWriting=true;const name=assetManagedBackupName({tag,version});try{const fileHandle=await handle.getFileHandle(name,{create:true}),writable=await fileHandle.createWritable();await writable.write(new Blob([createBackupZipBytes()],{type:'application/zip'}));await writable.close();await assetCleanupPhoneBackups(handle);const settings=assetBackupSettings();settings.phoneEnabled=true;settings.phonePermission='granted';settings.lastPhoneBackupAt=new Date().toISOString();persist(false);if(!silent)toast(`휴대폰 백업 완료: ${name}`);return true}catch(error){if(!silent)showNotice('휴대폰 백업 실패',String(error?.message||error));return false}finally{assetBackupWriting=false}}
async function assetConnectPhoneBackup(){if(typeof window.showDirectoryPicker!=='function'||!window.isSecureContext){showNotice('고정 폴더를 지원하지 않는 브라우저입니다.','ZIP 저장은 계속 사용할 수 있습니다. Android에서 폴더 선택이 보이지 않으면 다운로드 또는 Drive 공유를 이용해 주세요.');return false}try{const handle=await window.showDirectoryPicker({id:`asset-os-backup-${ASSET_BACKUP_ENV}`,mode:'readwrite',startIn:'downloads'});if(await assetBackupPermission(handle,true)!=='granted')throw new Error('폴더 쓰기 권한이 필요합니다.');await assetBackupHandleSet(handle);const settings=assetBackupSettings();settings.phoneEnabled=true;settings.phonePermission='granted';if(settings.lastReleaseVersion!==APP_VERSION){await assetWritePhoneBackup({tag:'pre',version:settings.lastReleaseVersion||'v0.4',silent:true});settings.lastReleaseVersion=APP_VERSION}persist(false);toast('휴대폰 백업 폴더를 연결했습니다.');return true}catch(error){if(error?.name!=='AbortError')showNotice('폴더 연결 실패',String(error?.message||error));return false}}
function queueAssetAutoBackup(){if(assetBackupWriting)return;clearTimeout(assetAutoBackupTimer);const settings=assetBackupSettings();if(!settings.phoneEnabled)return;assetAutoBackupTimer=setTimeout(()=>assetWritePhoneBackup({silent:true}),ASSET_AUTO_BACKUP_DELAY)}
async function assetCreateKeepBackup(){if(await assetWritePhoneBackup({tag:'keep'}))return true;const name=assetManagedBackupName({tag:'keep'});downloadBytes(createBackupZipBytes(),name);toast(`영구보관 ZIP 저장: ${name}`);return true}
