'use strict';
let pensionIncomeAnalysisMode='month',pensionIncomeSelectedPoint='',pensionIncomeYearRange='10y',pensionIncomeChartMode='bar';
function pensionCompactWon(v){v=Math.max(0,Number(v)||0);if(v>=1000000000000)return `${(v/1000000000000).toFixed(v>=10000000000000?0:1).replace(/\.0$/,'')}조`;if(v>=100000000)return `${(v/100000000).toFixed(v>=1000000000?0:1).replace(/\.0$/,'')}억`;if(v>=10000)return `${(v/10000).toFixed(v>=100000?0:1).replace(/\.0$/,'')}만`;return `${Math.round(v).toLocaleString('ko-KR')}원`}
function pensionHeroWon(v){v=Number(v)||0;return Math.abs(v)>=1000000000000?`${v<0?'-':''}${pensionCompactWon(Math.abs(v))}`:won(v)}
function pensionHeroSigned(v){v=Number(v)||0;return `${v>=0?'+':'-'}${Math.abs(v)>=1000000000000?pensionCompactWon(Math.abs(v)):won(Math.abs(v))}`}
function pensionReadableWon(v){v=Math.max(0,Math.round(Number(v)||0));if(v>=100000000)return displayWon(v);if(v>=10000)return `${nf.format(Math.round(v/10000))}만원`;return won(v)}
function pensionFutureHeadlineWon(v){v=Math.max(0,Math.round(Number(v)||0));return pensionReadableWon(v)}
function pensionFutureAmountClass(v){const c=amountClass(v);return c==='amount-xxlong'?'xxlong':c==='amount-xlong'?'xlong':c==='amount-long'?'long':''}
function incomeYearRangePoints(points,range='10y'){const arr=[...(points||[])],limit=range==='5y'?5:range==='10y'?10:range==='20y'?20:0;return limit?arr.slice(-limit):arr}
function incomeRecordSpanYears(records=[]){const months=[...(records||[])].map(x=>String(x.date||'').slice(0,7)).filter(x=>/^\d{4}-\d{2}$/.test(x)).sort();if(!months.length)return 0;const [ay,am]=months[0].split('-').map(Number),[by,bm]=months.at(-1).split('-').map(Number),count=Math.max(1,(by-ay)*12+(bm-am)+1);return Math.max(1,Math.ceil(count/12))}
function incomeYearRangeControls(range,attr,totalYears){return `<div class="income-year-range" aria-label="연도 범위">${[['5y','5년'],['10y','10년'],['20y','20년'],['all','전체']].map(([k,l])=>`<button class="${range===k?'active':''}" ${attr}="${k}">${k==='all'?`전체${totalYears>20?` ${totalYears}년`:''}`:l}</button>`).join('')}</div>`}
function incomeChartModeControls(mode,attr){return `<div class="income-chart-mode" aria-label="그래프 방식"><button class="${mode==='bar'?'active':''}" ${attr}="bar">수령액</button><button class="${mode==='line'?'active':''}" ${attr}="line">성장추이</button></div>`}
function incomeRangeSummaryMarkup(points,amountTerm='수령'){if(!points?.length)return'';const first=points[0],last=points.at(-1),sum=points.reduce((n,x)=>n+(Number(x.value??x.amount)||0),0);return `<div class="income-range-summary"><div><span>선택기간 ${escapeHtml(amountTerm)}</span><strong aria-label="${won(sum)}">${pensionCompactWon(sum)}</strong></div><div><span>${escapeHtml(first.key)} → ${escapeHtml(last.key)}</span><strong>${pensionCompactWon(first.value??first.amount)} → ${pensionCompactWon(last.value??last.amount)}</strong></div></div>`}
function incomeAxisMarkup(max,H=170,T=22,B=28){const CH=H-T-B,ticks=[max,max*.5,0];return `<svg class="income-y-svg" viewBox="0 0 42 ${H}" aria-hidden="true">${ticks.map((v,i)=>{const y=T+CH*(i/(ticks.length-1));return `<text class="income-axis" x="38" y="${y+3}" text-anchor="end">${pensionCompactWon(v)}</text>`}).join('')}</svg>`}
function commonIncomeChartMarkup(points,selectedKey,pointAttr,yearly=false,caption='막대를 누르면 해당 기간 수령액과 수익률을 확인합니다.',chartMode='bar',longRange=false){
 const normalized=points.map(x=>({key:String(x.key||''),label:String(x.label||''),short:String(x.short??(yearly?String(x.year||x.label||'').slice(-2):String(x.month||x.label||'').replace('월',''))),value:Math.max(0,Number(x.value??x.amount)||0)}));if(!normalized.length||!normalized.some(x=>x.value>0))return `<div class="chart-panel income-chart-panel"><div class="empty-state"><strong>아직 받은 내역이 없습니다.</strong><span>배당·이자가 기록되면 그래프가 표시됩니다.</span></div></div>`;const H=170,T=22,B=28,CH=H-T-B,maxRaw=Math.max(1,...normalized.map(x=>x.value)),max=pensionZeroAxisMax(maxRaw),per=yearly?(normalized.length>20?34:normalized.length>10?30:26):23,plotW=Math.max(278,normalized.length*per),step=plotW/Math.max(1,normalized.length),barW=Math.max(10,Math.min(22,step*.60)),labelEvery=yearly?(normalized.length<=10?1:Math.ceil(normalized.length/8)):1,pointsXY=normalized.map((x,i)=>({x:step*(i+.5),y:T+CH-(x.value/max)*CH,...x}));
 const grid=[0,.5,1].map(r=>{const y=T+CH*r;return `<line class="income-grid" x1="0" y1="${y}" x2="${plotW}" y2="${y}"></line>`}).join('');
 const xlabels=pointsXY.map((p,i)=>{const show=!yearly||i===0||i===pointsXY.length-1||i%labelEvery===0;return show?`<text class="income-axis income-x" x="${p.x.toFixed(2)}" y="${H-7}" text-anchor="middle">${escapeHtml(yearly?String(p.short):String(i+1))}</text>`:''}).join('');
 let marks='';
 if(chartMode==='line'&&yearly){const path=pointsXY.map((p,i)=>`${i?'L':'M'} ${p.x.toFixed(2)} ${p.y.toFixed(2)}`).join(' ');marks=`<path class="income-growth-line" d="${path}"></path>${pointsXY.map((p,i)=>{const selected=selectedKey===p.key;return `<g class="income-line-point ${selected?'active':''}" ${pointAttr}="${escapeHtml(p.key)}" tabindex="0" role="button" aria-label="${escapeHtml(p.label)} ${won(p.value)}"><rect class="income-line-hit" x="${(p.x-step/2).toFixed(2)}" y="${T}" width="${step.toFixed(2)}" height="${CH}"></rect><circle class="income-growth-dot" cx="${p.x.toFixed(2)}" cy="${p.y.toFixed(2)}" r="${selected?5:3.2}"></circle>${selected&&p.value>0?`<text class="income-value-label" x="${p.x.toFixed(2)}" y="${Math.max(11,p.y-8).toFixed(2)}" text-anchor="middle">${pensionCompactWon(p.value)}</text>`:''}</g>`}).join('')}`}
 else{marks=pointsXY.map((p,i)=>{const h=p.value<=0?0:(p.value/max)*CH,y=T+CH-h,selected=selectedKey===p.key;return `<g class="income-bar-group ${selected?'active':''} ${p.value<=0?'zero':''}" ${pointAttr}="${escapeHtml(p.key)}" tabindex="0" role="button" aria-label="${escapeHtml(p.label)} ${won(p.value)}"><rect class="income-bar-hit" x="${(p.x-step/2).toFixed(2)}" y="${T}" width="${step.toFixed(2)}" height="${CH}"></rect><rect class="income-bar" x="${(p.x-barW/2).toFixed(2)}" y="${y.toFixed(2)}" width="${barW.toFixed(2)}" height="${Math.max(0,h).toFixed(2)}" rx="4"></rect>${selected&&p.value>0?`<text class="income-value-label" x="${p.x.toFixed(2)}" y="${Math.max(11,y-6).toFixed(2)}" text-anchor="middle">${pensionCompactWon(p.value)}</text>`:''}</g>`}).join('')}
 return `<div class="chart-panel income-chart-panel"><div class="income-chart-shell">${incomeAxisMarkup(max,H,T,B)}<div class="income-chart-scroll ${longRange?'long-range':''}" ${longRange?'data-long-range="true"':''}><svg class="income-svg" viewBox="0 0 ${plotW} ${H}" style="width:${plotW}px;min-width:${plotW}px" role="img" aria-label="${yearly?(chartMode==='line'?'연도별 배당 성장추이':'연도별 배당 수령 그래프'):'월별 배당 수령 그래프'}">${grid}${marks}${xlabels}</svg></div></div><div class="chart-caption">${escapeHtml(caption)}</div></div>`
}
function commonIncomeAnalysisMarkup({mode,points=[],selected=null,rate=null,modeAttr,pointAttr,amountTerm='수령',rateTerm='수익률',focusNote='',recentHtml='',yearly=false,caption='',yearRange='10y',rangeAttr='',chartMode='bar',chartModeAttr='',totalYearCount=0}){
 const tabs=`<div class="period-switch">${[['month','월별'],['year','연도별'],['recent','최근 내역']].map(([k,l])=>`<button class="${mode===k?'active':''}" ${modeAttr}="${k}">${l}</button>`).join('')}</div>`,yearTools=yearly?`<div class="income-year-tools">${incomeYearRangeControls(yearRange,rangeAttr,totalYearCount||points.length)}${incomeChartModeControls(chartMode,chartModeAttr)}</div>${incomeRangeSummaryMarkup(points,amountTerm)}`:'',chart=mode==='recent'?'':commonIncomeChartMarkup(points,selected?.key||'',pointAttr,yearly,caption||`막대를 누르면 해당 기간 ${amountTerm}과 ${rateTerm}을 확인합니다.`,chartMode,yearly&&points.length>10),focus=selected?`<div class="period-yield-card"><div class="period-yield-head"><div><span>${escapeHtml(selected.label)} ${escapeHtml(amountTerm)}</span><strong>${won(selected.value??selected.amount)}</strong></div><div class="period-yield-rate">${rate==null?'계산 전':Number(rate).toFixed(2)+'%'}</div></div><small>${escapeHtml(focusNote)}</small></div>`:'';
 return `<div class="compact-dividend-analysis common-income-analysis">${tabs}${yearTools}${chart}${focus}${mode==='recent'?recentHtml:''}</div>`
}
function pensionIncomeAnalysisMarkup(scope,mode,selectedKey=''){
 const s=pensionIncomeSummary(scope),monthly=mode==='month',yearly=mode==='year',recent=mode==='recent',allYearPoints=pensionIncomeYears(scope),points=recent?[]:(monthly?pensionIncomeMonths(scope,s.year):incomeYearRangePoints(allYearPoints,pensionIncomeYearRange)),fallback=recent?null:points.filter(x=>x.amount>0).at(-1),rawSelected=recent?null:(points.find(x=>x.key===selectedKey)||fallback),selected=rawSelected?{...rawSelected,value:rawSelected.amount}:null,principal=selected?pensionIncomePrincipalAt(scope,selected.key,monthly?'month':'year'):0,selectedRate=selected?(principal?selected.value/principal*100:0):null,recentRows=recent?s.records.slice(0,3):[],recentHtml=`<div class="composition-holdings compact-income-detail"><div class="sectionhead"><h2 style="font-size:13px">최근 내역</h2><span class="count-pill">최대 3건</span></div><div class="dividend-list compact-dividend-list">${recentRows.length?recentRows.map(x=>{const h=pensionHoldingById(x.holdingId);return `<div class="dividend-row"><span class="rowcopy"><strong>${escapeHtml(h?.name||x.label||'종목')}</strong><small>${formatDate(x.date)} · ${x.type==='interest'?'이자':'배당'}${x.source==='source-archive'?' · 과거자료':''}</small></span><span class="rowamount positive">${won(x.amount)}</span></div>`}).join(''):'<div class="empty-state"><span>배당·이자 내역이 없습니다.</span></div>'}</div></div>`;
 return commonIncomeAnalysisMarkup({mode,points,selected,rate:selectedRate,modeAttr:'data-pension-income-mode',pointAttr:'data-pension-income-point',amountTerm:'수령',rateTerm:'배당률',focusNote:selected?(principal?`${monthly?'월말':'연말'} 투자원금 ${won(principal)} 기준`:'해당 기간 투자원금 스냅샷 없음'):'',recentHtml,yearly,caption:yearly&&pensionIncomeChartMode==='line'?'연간 수령액의 장기 성장 흐름입니다. 점을 누르면 해당 연도를 확인합니다.':'막대를 누르면 해당 기간 수령액과 배당률을 확인합니다.',yearRange:pensionIncomeYearRange,rangeAttr:'data-pension-income-range',chartMode:pensionIncomeChartMode,chartModeAttr:'data-pension-income-chart',totalYearCount:incomeRecordSpanYears(pensionIncomeRecords(scope))})
}
function captureIncomeChartScroll(){const e=$('.income-chart-scroll');if(!e)return null;const max=Math.max(0,e.scrollWidth-e.clientWidth);return{left:e.scrollLeft,max,ratio:max>0?e.scrollLeft/max:0,atEnd:max>0&&max-e.scrollLeft<=4}}
function restoreIncomeChartScroll(saved,preferLatest=false){requestAnimationFrame(()=>{const e=$('.income-chart-scroll');if(!e)return;const max=Math.max(0,e.scrollWidth-e.clientWidth);let left=0;if(saved&&max>0&&saved.max>0){if(saved.atEnd)left=max;else if(Math.abs(max-saved.max)<=2)left=Math.max(0,Math.min(max,saved.left));else left=Math.max(0,Math.min(max,max*saved.ratio))}else if(max>0&&preferLatest)left=max;e.scrollLeft=left})}
function pensionIncomeAnalysisSheetMarkup(scope=pensionAssetScope()){const x=pensionIncomeSummary(scope),latest=x.records[0];return `<div class="analysis-sheet-summary"><div class="dividend-metrics compact-four"><div class="dividend-metric emphasis"><span>누적 수령</span><strong>${won(x.total)}</strong></div><div class="dividend-metric"><span>${x.year}년 수령</span><strong>${won(x.yearTotal)}</strong></div><div class="dividend-metric"><span>${x.year} 배당률</span><strong>${x.yieldRate.toFixed(2)}%</strong></div><div class="dividend-metric"><span>최근 수령</span><strong>${latest?won(latest.amount):'-'}</strong><small>${latest?escapeHtml(pensionHoldingById(latest.holdingId)?.name||latest.label||'종목'):'내역 없음'}</small></div></div></div>${pensionIncomeAnalysisMarkup(scope,pensionIncomeAnalysisMode,pensionIncomeSelectedPoint)}`}
function bindPensionIncomeAnalysis(){const selectPoint=key=>{pensionIncomeSelectedPoint=key;renderPensionIncomeAnalysis(false)};$$('[data-pension-income-mode]').forEach(b=>b.onclick=()=>{pensionIncomeAnalysisMode=['month','year','recent'].includes(b.dataset.pensionIncomeMode)?b.dataset.pensionIncomeMode:'month';pensionIncomeSelectedPoint='';renderPensionIncomeAnalysis(true)});$$('[data-pension-income-range]').forEach(b=>b.onclick=()=>{pensionIncomeYearRange=['5y','10y','20y','all'].includes(b.dataset.pensionIncomeRange)?b.dataset.pensionIncomeRange:'10y';pensionIncomeSelectedPoint='';renderPensionIncomeAnalysis(true)});$$('[data-pension-income-chart]').forEach(b=>b.onclick=()=>{pensionIncomeChartMode=b.dataset.pensionIncomeChart==='line'?'line':'bar';pensionIncomeSelectedPoint='';renderPensionIncomeAnalysis(false)});$$('[data-pension-income-point]').forEach(b=>{b.onclick=()=>selectPoint(b.dataset.pensionIncomePoint);b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectPoint(b.dataset.pensionIncomePoint)}}})}
function renderPensionIncomeAnalysis(preferLatest=false){const body=$('#sheetBody');if(!body)return;const saved=captureIncomeChartScroll();body.innerHTML=pensionIncomeAnalysisSheetMarkup(pensionAssetScope());bindPensionIncomeAnalysis();restoreIncomeChartScroll(saved,preferLatest)}
function openPensionIncomeAnalysis(){pensionIncomeAnalysisMode='month';pensionIncomeSelectedPoint='';pensionIncomeYearRange='10y';pensionIncomeChartMode='bar';$('#sheetEyebrow').textContent=pensionAssetScope()==='irp'?'IRP':'개인연금';$('#sheetTitle').textContent='배당·이자 분석';$('#sheetBody').innerHTML=pensionIncomeAnalysisSheetMarkup(pensionAssetScope());openSheet('#detailSheet',{variant:'income-analysis'});setTimeout(bindPensionIncomeAnalysis,0)}
