'use strict';
function insurancePolicies(){return state.insurance?.policies||[]}
function insuranceMonthlyPremium(asOf=localYmd()){return insurancePolicies().filter(p=>p.status==='active'&&p.paymentStyle==='monthly'&&(!p.contractDate||p.contractDate<=asOf)&&(!p.paymentEndDate||asOf<=p.paymentEndDate)).reduce((n,p)=>n+(Number(p.premium)||0),0)}
function insuranceMonthsInclusive(start,end){const a=String(start||'').match(/^(\d{4})-(\d{2})/),b=String(end||'').match(/^(\d{4})-(\d{2})/);if(!a||!b)return 0;return Math.max(0,(Number(b[1])-Number(a[1]))*12+Number(b[2])-Number(a[2])+1)}
function insurancePremiumSummary(p,asOf=localYmd()){
 const premium=Math.max(0,Number(p?.premium)||0),start=String(p?.contractDate||''),end=String(p?.paymentEndDate||''),cutoff=p?.status==='ended'?String(p.endedAt||end):end;
 const total=Math.max(0,Number(p?.totalPremium)||(p?.paymentStyle==='lump'?premium:insuranceMonthsInclusive(start,end)*premium));
 const scheduleIds=new Set(financeSchedules().filter(s=>s.kind==='insurance'&&String(s.productId||'')===String(p.id)).map(s=>s.id));
 const rows=typeof integratedOperationalLedger==='function'?integratedOperationalLedger():[];
 const payments=rows.filter(t=>['expense','externalExpense'].includes(t.type)&&t.status!=='cancelled'&&String(t.date)<=asOf&&(t.productId===p.id||scheduleIds.has(t.meta?.scheduleId))),paymentIds=new Set(payments.map(t=>t.id)),refunds=rows.filter(t=>t.type==='refund'&&String(t.date)<=asOf&&paymentIds.has(t.meta?.refundOf)).reduce((n,t)=>n+(Number(t.amount)||0),0),paid=Math.max(0,payments.reduce((n,t)=>n+(Number(t.amount)||0),0)-refunds);
 const nextMonth=asOf.slice(0,7)==='9999-12'?'':`${Number(asOf.slice(0,4))+(Number(asOf.slice(5,7))===12?1:0)}-${String(Number(asOf.slice(5,7))%12+1).padStart(2,'0')}-01`;
 const remaining=p?.status==='ended'?0:p?.paymentStyle==='lump'?(start>asOf?premium:0):nextMonth?insuranceMonthsInclusive(start>nextMonth?start:nextMonth,cutoff)*premium:0;
 return{total,paid,remaining,previousRecorded:Math.max(0,Number(p?.paidPremium)||0)}
}
function insuranceSchedule(policy){if(!policy?.id)return null;return financeSchedules().find(s=>s.kind==='insurance'&&String(s.productId||'')===String(policy.id))||null}
function insuranceCoverageText(rows=[]){return rows.map(c=>[c.name,Number(c.amount)||'',c.note||''].join(' | ')).join('\n')}
function parseInsuranceCoverages(value){return String(value||'').split(/\r?\n/).map(line=>line.trim()).filter(Boolean).map(line=>{const [name='',amount='',...note]=line.split('|').map(x=>x.trim());return{name,amount:Math.max(0,Number(String(amount).replace(/,/g,''))||0),note:note.join(' | ')}}).filter(c=>c.name)}
function syncInsuranceSchedule(policy,linkSchedule=true){let schedule=insuranceSchedule(policy);if(!linkSchedule){if(schedule){schedule.active=false;schedule.endDate=schedule.endDate||localYmd()}return null}if(policy.paymentStyle!=='monthly'||policy.status==='ended'||!Number(policy.premium)){if(schedule){schedule.active=false;schedule.endDate=policy.endedAt||policy.paymentEndDate||localYmd()}return schedule||null}if(!schedule){const matches=financeSchedules().filter(s=>s.kind==='insurance'&&!s.productId&&normalizeName(s.name)===normalizeName(policy.name)&&Math.abs((Number(s.amount)||0)-(Number(policy.premium)||0))<.5);if(matches.length===1)schedule=matches[0]}const next={id:schedule?.id||`schedule-insurance-${policy.id}`,name:policy.name,kind:'insurance',amount:Number(policy.premium)||0,amountMode:'fixed',day:Math.min(31,Math.max(0,Number(policy.paymentDay)||0)),recurrence:'monthly',startDate:policy.contractDate||'',endDate:policy.paymentEndDate||'',targetKind:'',targetAccountId:'',targetPensionAccountId:'',targetIsaAccountId:'',productId:policy.id,liabilityId:'',active:true,note:`${policy.company||'보험사 미입력'} · 보험료`,source:'insurance-policy',needsDate:!Number(policy.paymentDay),attention:!Number(policy.paymentDay)?'date-required':''};if(schedule)Object.assign(schedule,next);else financeSchedules().push(next);return next}
function insuranceCardMarkup(p){const schedule=insuranceSchedule(p);return `<button class="finance-product-card ${p.status==='ended'?'ended':''}" data-insurance-id="${escapeHtml(p.id)}"><div><strong>${escapeHtml(p.name)} <span class="finance-status-pill ${p.status==='active'?'active':''}">${p.status==='active'?'유지':'종료'}</span></strong><small>${escapeHtml(p.company||'보험사 미입력')} · ${escapeHtml(p.category||'분류 미입력')}<br>${p.paymentStyle==='lump'?'일시납':`월 ${won(p.premium)}`} · ${p.paymentStyle==='lump'?'반복 일정 없음':schedule?.active&&!schedule.needsDate?`${schedule.day}일 일정 연결`:p.status==='ended'?'일정 종료':'일정 연결 안 됨'}</small></div><b>›</b></button>`}
function openInsuranceHub(){const rows=insurancePolicies(),active=rows.filter(p=>p.status==='active'),ended=rows.filter(p=>p.status==='ended'),monthly=insuranceMonthlyPremium();$('#sheetEyebrow').textContent='보장성 보험';$('#sheetTitle').textContent='내 보험';$('#sheetBody').innerHTML=`<div class="sheetrows"><div class="sheetrow total"><span>현재 월 보험료</span><strong>${won(monthly)}</strong></div></div><div class="policy-toolbar"><strong>유지 중 ${active.length}건</strong><button data-insurance-new>＋ 보험 추가</button></div><div class="finance-product-list">${active.map(insuranceCardMarkup).join('')||'<div class="integrated-empty">유지 중인 보험이 없습니다.</div>'}</div>${ended.length?`<div class="finance-archive-title">종료된 보험 · ${ended.length}건</div><div class="finance-product-list">${ended.map(insuranceCardMarkup).join('')}</div>`:''}`;openSheet('#detailSheet');$('[data-insurance-new]')?.addEventListener('click',()=>openInsuranceForm());$$('[data-insurance-id]').forEach(b=>b.onclick=()=>openInsuranceDetail(b.dataset.insuranceId))}
function openInsuranceDetail(id){const p=insurancePolicies().find(x=>x.id===id);if(!p)return;$('#sheetEyebrow').textContent='보험 · 계약';$('#sheetTitle').textContent=p.name;const premium=insurancePremiumSummary(p),schedule=insuranceSchedule(p),rows=[['보험사',p.company],['분류',p.category],['계약일',p.contractDate],['보장 만기',p.coverageEndDate],['납입 종료',p.paymentEndDate],['보험료',p.paymentStyle==='lump'?won(p.premium):`월 ${won(p.premium)}`],['납부 일정',p.paymentStyle==='lump'?'반복 일정 없음':p.status==='ended'?'일정 종료':schedule?.active?(schedule.needsDate?'납부일 확인 필요':`매월 ${schedule.day}일`):'연결 안 됨'],['계약 총 보험료 · 예상',won(premium.total)],['실제 납부 기록',won(premium.paid)],...(premium.previousRecorded?[['기존 등록 누계 · 별도',won(premium.previousRecorded)]]:[]),['다음 달 이후 · 예상',won(premium.remaining)]];$('#sheetBody').innerHTML=`<div class="sheetrows">${rows.map(([k,v])=>`<div class="sheetrow"><span>${escapeHtml(k)}</span><strong>${escapeHtml(v||'-')}</strong></div>`).join('')}</div><div class="policy-toolbar"><strong>보장 항목 ${p.coverages.length}개</strong></div><div class="sheetrows">${p.coverages.map(c=>`<div class="sheetrow"><span>${escapeHtml(c.name)}${c.note?`<small style="display:block">${escapeHtml(c.note)}</small>`:''}</span><strong>${won(c.amount)}</strong></div>`).join('')||'<div class="integrated-empty">보장 항목이 없습니다.</div>'}</div>${p.note?`<div class="source-note">${escapeHtml(p.note)}</div>`:''}<button class="diagnostic-action" data-insurance-payment="${escapeHtml(p.id)}">납부 기록</button>${p.status==='active'?`<div class="finance-detail-actions"><button class="primary" data-insurance-edit="${escapeHtml(p.id)}">계약 수정</button><button class="danger" data-insurance-end="${escapeHtml(p.id)}">종료 처리</button></div>`:''}`;openSheet('#detailSheet');$('[data-insurance-payment]')?.addEventListener('click',()=>openInsurancePaymentForm(id));$('[data-insurance-edit]')?.addEventListener('click',()=>openInsuranceForm(id));$('[data-insurance-end]')?.addEventListener('click',()=>endInsurancePolicy(id))}
function openInsuranceForm(id=''){const p=insurancePolicies().find(x=>x.id===id)||null,schedule=insuranceSchedule(p);$('#formEyebrow').textContent='보험 · 계약 관리';$('#formTitle').textContent=p?'보험 계약 수정':'보험 추가';$('#formBody').innerHTML=`<form id="insuranceForm" class="form" data-insurance-id="${escapeHtml(p?.id||'')}"><div class="form-grid"><div class="field"><label>보험명</label><input name="name" value="${escapeHtml(p?.name||'')}" required></div><div class="field"><label>보험사</label><input name="company" value="${escapeHtml(p?.company||'')}"></div></div><div class="field"><label>분류</label><input name="category" value="${escapeHtml(p?.category||'')}" placeholder="예: 실손·건강·운전자"></div><div class="form-grid"><div class="field"><label>계약일</label><input name="contractDate" type="date" value="${escapeHtml(p?.contractDate||'')}"></div><div class="field"><label>보장 만기</label><input name="coverageEndDate" type="date" value="${escapeHtml(p?.coverageEndDate||'')}"></div></div><div class="form-grid"><div class="field"><label>납입 종료</label><input name="paymentEndDate" type="date" value="${escapeHtml(p?.paymentEndDate||'')}"></div><div class="field"><label>납입 방식</label><select name="paymentStyle"><option value="monthly" ${p?.paymentStyle!=='lump'?'selected':''}>월납</option><option value="lump" ${p?.paymentStyle==='lump'?'selected':''}>일시납</option></select></div></div><div class="form-grid"><div class="field"><label>보험료</label><input name="premium" type="number" min="0" step="1" inputmode="numeric" value="${escapeHtml(Number(p?.premium)||'')}" required></div><div class="field"><label>월 납부일</label><input name="paymentDay" type="number" min="1" max="31" value="${escapeHtml(Number(p?.paymentDay)||Number(schedule?.day)||'')}" placeholder="확인 후 입력"></div></div><label class="insurance-schedule-link"><input name="linkSchedule" type="checkbox" ${schedule||!p?'checked':''}><span>보험료를 통합 일정과 연결</span></label><div class="field"><label>보장 항목 <small>한 줄에 이름 | 금액 | 메모</small></label><textarea name="coverages" rows="6" placeholder="입원의료비 | 50000000 | 갱신형">${escapeHtml(insuranceCoverageText(p?.coverages||[]))}</textarea></div><div class="field"><label>메모</label><input name="note" value="${escapeHtml(p?.note||'')}"></div><button class="integrated-form-save">${p?'수정 저장':'보험 저장'}</button></form>`;openSheet('#formSheet',{mode:'input'});$('#insuranceForm').onsubmit=e=>{e.preventDefault();saveInsurancePolicy(e.currentTarget)}}
function saveInsurancePolicy(form){const d=new FormData(form),id=form.dataset.insuranceId||uid('insurance'),old=insurancePolicies().find(x=>x.id===id),name=String(d.get('name')||'').trim(),premium=Math.max(0,Math.round(Number(d.get('premium'))||0)),paymentDay=Math.min(31,Math.max(0,Math.round(Number(d.get('paymentDay'))||0)));if(!name)return toast('보험명을 입력해 주세요.');if(!premium)return toast('보험료를 입력해 주세요.');const p={...(old||{}),id,name,company:String(d.get('company')||'').trim(),category:String(d.get('category')||'').trim(),premium,paymentDay,paymentStyle:String(d.get('paymentStyle'))==='lump'?'lump':'monthly',contractDate:String(d.get('contractDate')||''),coverageEndDate:String(d.get('coverageEndDate')||''),paymentEndDate:String(d.get('paymentEndDate')||''),status:old?.status||'active',coverages:parseInsuranceCoverages(d.get('coverages')),note:String(d.get('note')||'').trim()};if(p.contractDate&&p.paymentEndDate&&p.paymentEndDate<p.contractDate)return toast('납입 종료일은 계약일보다 빠를 수 없습니다.');if(old)Object.assign(old,p);else insurancePolicies().push(p);syncInsuranceSchedule(p,d.get('linkSchedule')==='on');if(!persist())return;sheetDirty=false;closeSheets();render();setTimeout(openInsuranceHub,60);toast(old?'보험 계약을 수정했습니다.':'보험과 납부 일정을 저장했습니다.')}
function endInsurancePolicy(id){const p=insurancePolicies().find(x=>x.id===id);if(!p)return;showDialog({title:'보험 계약을 종료할까요?',message:'보험 기록과 과거 납부내역은 보존하고 앞으로의 연결 일정만 종료합니다.',confirmText:'종료',cancelText:'취소'},()=>{p.status='ended';p.endedAt=localYmd();const schedule=insuranceSchedule(p);if(schedule){schedule.active=false;schedule.endDate=p.endedAt}if(!persist())return;closeSheets();render();setTimeout(openInsuranceHub,60);toast('보험 계약을 종료 보관했습니다.')})}

function recordInsurancePayment(id,{date,amount,source='tracked',paymentId=''}){
 const p=insurancePolicies().find(x=>x.id===id);if(!p)return{ok:false,error:'보험 계약을 찾지 못했습니다.'};
 const error=postedDateError(date);if(error)return{ok:false,error};
 if(p.contractDate&&date<p.contractDate)return{ok:false,error:'계약일 이전에는 납부를 기록할 수 없습니다.'};
 if((p.endedAt&&date>p.endedAt)||(p.paymentEndDate&&date>p.paymentEndDate))return{ok:false,error:'납입 종료일 이후입니다. 계약 기간을 확인해 주세요.'};
 if(!Number.isFinite(Number(amount))||Number(amount)<=0)return{ok:false,error:'납부 금액을 1원 이상 입력해 주세요.'};
 const ledger=integratedStore().ledger;if(paymentId&&ledger.some(t=>t.id===paymentId))return{ok:false,error:'이미 저장한 납부 기록입니다.'};
 const tx={id:paymentId||uid('insurance-payment'),date,type:source==='outside'?'externalExpense':'expense',amount:Number(amount),fromAccountId:source==='outside'?undefined:'cash-main',category:p.name+' 보험료',productId:id,fixed:true,meta:{insurancePayment:true}};
 const err=integratedValidateCandidate(tx,'');if(err)return{ok:false,error:err};ledger.push(tx);return{ok:true,transaction:tx}
}
function openInsurancePaymentForm(id){
 const p=insurancePolicies().find(x=>x.id===id);if(!p)return;
 $('#formEyebrow').textContent='보험 · 실제 납부';$('#formTitle').textContent='보험료 납부 기록';
 $('#formBody').innerHTML=`<form id="insurancePaymentForm" class="form"><div class="form-grid"><div class="field"><label>납부일</label><input name="date" type="date" value="${escapeHtml(ymd())}" required></div><div class="field"><label>실제 납부액</label><input name="amount" type="number" min="1" step="1" value="${escapeHtml(Number(p.premium)||'')}" required></div></div><div class="field"><label>지급 계좌</label><select name="source"><option value="tracked">현금·입출금</option><option value="outside">앱 밖 계좌</option></select></div><div class="source-note">일정에서 이미 완료한 납부는 다시 입력하지 않습니다.</div><button class="integrated-form-save">납부 저장</button></form>`;
 openSheet('#formSheet',{mode:'input'});const paymentId=uid('insurance-payment');$('#insurancePaymentForm').onsubmit=e=>{e.preventDefault();const d=new FormData(e.currentTarget),r=recordInsurancePayment(id,{date:String(d.get('date')||''),amount:Number(d.get('amount')),source:String(d.get('source')||'tracked'),paymentId});if(!r.ok)return toast(r.error);setting().integratedMonth=integratedMonthKey(r.transaction.date);setting().integratedLedgerFilter='all';if(!persist())return;sheetDirty=false;closeSheets();render();setTimeout(()=>openInsuranceDetail(id),60);toast('실제 납부 기록을 저장했습니다.')}
}
