'use strict';
const ISA_QUOTE_REFRESH_MS=10*60*1000;
let isaQuoteRefreshPromise=null;
function isaQuoteLinks(a=currentAccount()){return (a?.holdings||[]).filter(h=>h.lifecycleStatus!=='archived'&&h.quoteSource==='kis'&&h.instrumentCode&&['stock','bond'].includes(h.quoteType)).map(h=>({holdingId:h.id,type:h.quoteType,code:String(h.instrumentCode).trim().toUpperCase()}))}
function isaQuoteRefreshDue(a=currentAccount(),now=Date.now()){const links=isaQuoteLinks(a);if(!links.length)return false;const last=Math.min(...links.map(x=>new Date((a.holdings.find(h=>h.id===x.holdingId)?.quoteUpdatedAt)||0).getTime()||0));return now-last>=ISA_QUOTE_REFRESH_MS}
function applyIsaQuoteResults(a,quotes,fetchedAt){const before={cash:a.baselineCash,transactions:JSON.stringify(a.transactions||[]),positions:(a.holdings||[]).map(h=>[h.id,h.baselineQty,h.baselineAvg])},byKey=new Map((quotes||[]).map(q=>[`${q.type}:${String(q.code||'').toUpperCase()}`,q]));let updated=0;for(const h of a.holdings||[]){const quote=byKey.get(`${h.quoteType}:${String(h.instrumentCode||'').toUpperCase()}`);if(!quote||!(Number(quote.price)>0))continue;h.currentPrice=Number(quote.price);h.quoteUpdatedAt=fetchedAt||new Date().toISOString();h.quoteStatus='ok';h.quoteError='';updated++}const unchanged=before.cash===a.baselineCash&&before.transactions===JSON.stringify(a.transactions||[])&&before.positions.every(([id,qty,avg])=>{const h=a.holdings.find(x=>x.id===id);return h&&h.baselineQty===qty&&h.baselineAvg===avg});return{ok:unchanged,updated,error:unchanged?'':'QUOTE_MUTATED_FIXED_DATA'}}
async function refreshIsaQuotes({manual=false}={}){const a=currentAccount();if(!a)return{ok:false,error:'ISA_ACCOUNT_MISSING'};const links=isaQuoteLinks(a);if(!links.length)return{ok:false,error:'ISA_QUOTES_NOT_LINKED'};if(isaQuoteRefreshPromise)return isaQuoteRefreshPromise;isaQuoteRefreshPromise=(async()=>{const result=await brokerKisClient.quotes(links.map(({type,code})=>({type,code})));if(!result.ok)return result;const snapshot=clone(a),applied=applyIsaQuoteResults(a,result.data.quotes,result.data.fetchedAt);if(!applied.ok){Object.assign(a,snapshot);return applied}if(!persist(false)){Object.assign(a,snapshot);return{ok:false,error:'PERSIST_FAILED'}}if(manual){renderKeepingScroll();toast(`현재가 ${applied.updated}개 갱신 · 수량·매입가 유지`)}return{ok:true,updated:applied.updated,fetchedAt:result.data.fetchedAt}})().catch(error=>({ok:false,error:String(error?.message||'QUOTE_REFRESH_FAILED')})).finally(()=>{isaQuoteRefreshPromise=null});return isaQuoteRefreshPromise}
function maybeAutoRefreshIsaQuotes(){if(route().root!=='isa'||!state.accounts.length||!brokerKisClient.authState().signedIn||!isaQuoteRefreshDue())return;refreshIsaQuotes().then(result=>{if(result.ok)renderKeepingScroll()})}
document.addEventListener('click',async event=>{const button=event.target.closest?.('[data-isa-quote-refresh]');if(!button)return;button.disabled=true;button.textContent='조회 중';const result=await refreshIsaQuotes({manual:true});if(!result.ok){button.disabled=false;button.textContent='지금 갱신';toast(result.error==='BROKER_AUTH_REQUIRED'?'한국투자 연결 로그인이 필요합니다.':`현재가 갱신 실패 · ${result.error}`)}})
