'use strict';
function pensionAssetScope(){return ['all','pension','irp'].includes(setting().pensionAssetScope)?setting().pensionAssetScope:'all'}
function pensionAssetLens(){return 'assetClass'}
function pensionHoldingAccount(h){return pensionAccount(h.accountId)}
function pensionHoldingValue(h){return (Number(h.qty)||0)*(Number(h.currentPrice)||0)}
function pensionHoldingCost(h){return (Number(h.qty)||0)*(Number(h.avgPrice)||0)}
function pensionScopedHoldings(scope=pensionAssetScope()){
 return pensionStore().holdings.filter(h=>{const a=pensionHoldingAccount(h);if(!a||a.status!=='active')return false;return scope==='all'||a.kind===scope})
}
function pensionAccountCash(accountId){let total=0;for(const x of centralPensionContributionRows())if(x.accountId===accountId)total+=Number(x.amount)||0;for(const t of pensionStore().transactions||[])if(t.accountId===accountId)total+=pensionTradeCashDelta(t);return total}
function pensionCentralCash(scope=pensionAssetScope()){let total=0;const accounts=new Map(pensionStore().accounts.map(a=>[a.id,a]));for(const x of centralPensionContributionRows()){const a=accounts.get(x.accountId),kind=a?.kind||x.kind;if(scope!=='all'&&kind!==scope)continue;if(a&&a.status!=='active')continue;total+=Math.max(0,Number(x.amount)||0)}for(const t of pensionStore().transactions||[]){const a=accounts.get(t.accountId);if(!a||a.status!=='active')continue;if(scope!=='all'&&a.kind!==scope)continue;total+=pensionTradeCashDelta(t)}return Math.max(0,total)}
function pensionAccountExposure(accountId){const holdings=pensionStore().holdings.filter(h=>h.accountId===accountId),qty=holdings.reduce((n,h)=>n+Math.max(0,Number(h.qty)||0),0),value=holdings.reduce((n,h)=>n+pensionHoldingValue(h),0),cash=pensionAccountCash(accountId);return{qty,value,cash,hasAssets:qty>1e-8||Math.abs(cash)>.5}}
function createPensionAccount(input={}){const kind=input.kind==='irp'?'irp':'pension',openedAt=String(input.openedAt||ymd()),dateError=postedDateError(openedAt);if(dateError)return{ok:false,error:dateError};const name=String(input.name||'').trim()||`${pensionAccountKindLabel(kind)} ${pensionStore().accounts.filter(a=>a.kind===kind).length+1}`,account={id:uid(kind==='irp'?'irp':'ps'),kind,name,provider:String(input.provider||'').trim(),status:'active',openedAt,closedAt:'',policyId:policyGroup(kind).activePolicyId||'',policyHistory:[]};pensionStore().accounts.push(account);return{ok:true,account}}
function archivePensionAccount(accountId){const a=pensionAccount(accountId);if(!a||a.status!=='active')return{ok:false,error:'운영 중인 계좌가 아닙니다.'};const e=pensionAccountExposure(accountId);if(e.hasAssets)return{ok:false,error:`보유자산 또는 계좌 현금이 남아 있습니다. 종목 ${num(e.qty)}주 · 현금 ${won(e.cash)}`};a.status='archived';a.closedAt=ymd();return{ok:true,account:a}}
function reopenPensionAccount(accountId){const a=pensionAccount(accountId);if(!a||a.status==='active')return{ok:false,error:'재개할 보관 계좌가 아닙니다.'};a.status='active';a.closedAt='';return{ok:true,account:a}}
function pensionAssetMetrics(scope=pensionAssetScope()){
 const holdings=pensionScopedHoldings(scope),holdingValue=holdings.reduce((s,h)=>s+pensionHoldingValue(h),0),holdingCost=holdings.reduce((s,h)=>s+pensionHoldingCost(h),0),cash=pensionCentralCash(scope),value=holdingValue+cash,cost=holdingCost+cash,profit=holdingValue-holdingCost,accounts=pensionStore().accounts.filter(a=>a.status==='active'&&(scope==='all'||a.kind===scope)).length;
 return{scope,holdings,cash,holdingValue,holdingCost,value,cost,profit,rate:cost?profit/cost*100:0,accounts}
}
function pensionAssetScopeLabel(scope=pensionAssetScope()){return scope==='pension'?'연금저축':scope==='irp'?'IRP':'전체'}
function pensionAssetModel(scope=pensionAssetScope(),lens='assetClass'){
 const m=pensionAssetMetrics(scope),colors=['#2f6fed','#15977e','#735ddd','#d18a1f','#7b8798'],groups=new Map();
 for(const h of m.holdings){const key=investmentRoleForHolding(h),entry=groups.get(key)||{key,name:key,value:0,cost:0,count:0,holdingIds:[]};entry.value+=pensionHoldingValue(h);entry.cost+=pensionHoldingCost(h);entry.count++;entry.holdingIds.push(h.id);groups.set(key,entry)}
 if(m.cash>0){const key='현금',entry=groups.get(key)||{key,name:key,value:0,cost:0,count:0,holdingIds:[]};entry.value+=m.cash;entry.cost+=m.cash;groups.set(key,entry)}
 const order=INVESTMENT_ROLES;const arr=[...groups.values()].sort((a,b)=>{const ai=order.indexOf(a.key),bi=order.indexOf(b.key);return (ai<0?999:ai)-(bi<0?999:bi)||b.value-a.value}),total=arr.reduce((s,x)=>s+x.value,0)||1;let acc=0;
 const segments=arr.map((x,i)=>{const start=acc,pct=x.value/total*100;acc+=pct;return{...x,pct,start,end:acc,color:colors[i%colors.length],profit:x.value-x.cost}});return{...m,lens:'investmentRole',segments,total}
}
function pensionAssetGroupHoldings(scope,role){const m=pensionAssetMetrics(scope);return m.holdings.filter(h=>investmentRoleForHolding(h)===role).sort((a,b)=>pensionHoldingValue(b)-pensionHoldingValue(a)||String(a.name).localeCompare(String(b.name),'ko'))}
function pensionRiskMetrics(){const m=pensionAssetMetrics('irp'),risky=m.holdings.filter(h=>h.risky).reduce((s,h)=>s+pensionHoldingValue(h),0),ratio=m.value?risky/m.value*100:0,limit=Math.max(0,Math.min(100,(Number(policy('irp').riskyAssetLimit)||.70)*100));return{...m,risky,ratio,limit,remaining:limit-ratio}}
function pensionIncomeRecords(scope=pensionAssetScope()){
 const allowedAccounts=new Set(pensionStore().accounts.filter(a=>scope==='all'||a.kind===scope).map(a=>a.id)),allowedHoldings=new Set(pensionStore().holdings.filter(h=>allowedAccounts.has(h.accountId)).map(h=>h.id)),legacy=pensionStore().incomes.filter(x=>allowedAccounts.has(x.accountId)&&(x.holdingId?allowedHoldings.has(x.holdingId):true)),txIncome=(pensionStore().transactions||[]).filter(t=>['dividend','interest'].includes(t.type)&&allowedAccounts.has(t.accountId)&&(t.holdingId?allowedHoldings.has(t.holdingId):true)).map(t=>({id:t.id,accountId:t.accountId,holdingId:t.holdingId,type:t.type,date:t.date,amount:Math.max(0,(Number(t.amount)||0)-(Number(t.fee)||0)-(Number(t.tax)||0)),source:'transaction'}));return [...legacy,...txIncome].sort((a,b)=>String(b.date).localeCompare(String(a.date))||String(b.id).localeCompare(String(a.id)))
}
function pensionIncomePrincipalAt(scope,key='',mode=''){const rows=pensionSnapshotRows(scope);if(!rows.length)return pensionAssetMetrics(scope).cost;let end=localYmd();if(mode==='month'&&/^\d{4}-\d{2}$/.test(String(key))){const [y,m]=String(key).split('-').map(Number);end=localYmd(new Date(y,m,0))}else if(mode==='year'&&/^\d{4}$/.test(String(key)))end=`${key}-12-31`;const snap=rows.filter(x=>String(x.date||'')<=end).at(-1);return Math.max(0,Number(snap?.cost)||0)}
function pensionIncomeRate(scope,amount,key='',mode=''){const cost=key?pensionIncomePrincipalAt(scope,key,mode):pensionAssetMetrics(scope).cost;return cost?(Number(amount)||0)/cost*100:0}
function pensionIncomeSummary(scope=pensionAssetScope()){
 const records=pensionIncomeRecords(scope),year=String(new Date().getFullYear()),total=records.reduce((s,x)=>s+(Number(x.amount)||0),0),yearTotal=records.filter(x=>String(x.date).startsWith(year)).reduce((s,x)=>s+(Number(x.amount)||0),0),yieldRate=pensionIncomeRate(scope,yearTotal,year,'year'),totalYieldRate=pensionIncomeRate(scope,total);return{records,total,yearTotal,yieldRate,totalYieldRate,year,count:records.length}
}
function pensionIncomeMonths(scope=pensionAssetScope(),year=String(new Date().getFullYear())){const rows=Array.from({length:12},(_,i)=>({key:`${year}-${String(i+1).padStart(2,'0')}`,month:i+1,label:`${i+1}월`,amount:0}));for(const x of pensionIncomeRecords(scope).filter(x=>String(x.date).startsWith(year))){const m=Number(String(x.date).slice(5,7));if(rows[m-1])rows[m-1].amount+=Number(x.amount)||0}return rows}
function pensionIncomeYears(scope=pensionAssetScope()){const current=new Date().getFullYear(),recordYears=pensionIncomeRecords(scope).map(x=>Number(String(x.date).slice(0,4))).filter(Number.isFinite),first=recordYears.length?Math.min(...recordYears):current-4,start=Math.min(first,current-4),years=[];for(let y=start;y<=current;y++){const amount=pensionIncomeRecords(scope).filter(x=>String(x.date).startsWith(String(y))).reduce((sum,x)=>sum+(Number(x.amount)||0),0);years.push({key:String(y),year:y,label:String(y),amount})}return years}
function pensionProjection(){const p=pensionStore().projection||{},m=pensionAssetMetrics('all'),currentYear=new Date().getFullYear(),birthYear=Math.max(1900,Math.min(currentYear,Math.round(Number(p.birthYear)||Number(seed.pension.projection.birthYear)||1995))),retirementAge=Math.max(1,Math.min(100,Math.round(Number(p.retirementAge)||Number(seed.pension.projection.retirementAge)||65))),currentAge=Math.max(0,currentYear-birthYear),years=Math.max(0,retirementAge-currentAge),monthly=Math.max(0,Number(p.monthlyContribution)||0),annual=Math.max(0,Number(p.annualReturn)||0),r=annual/12,n=Math.round(years*12),future=r>0?m.value*Math.pow(1+r,n)+monthly*(Math.pow(1+r,n)-1)/r:m.value+monthly*n,withdrawal=Math.max(0,Number(p.withdrawalRate)||0),inflation=Math.max(0,Number(p.inflationRate)||0),monthlyPension=future*withdrawal/12,futureReal=inflation>0?future/Math.pow(1+inflation,years):future,monthlyPensionReal=futureReal*withdrawal/12;return{...p,birthYear,current:m.value,years,yearsToRetire:years,monthly,annual,future,withdrawal,monthlyPension,inflation,retirementAge,currentAge,futureReal,monthlyPensionReal}}
function pensionPerformanceContribution(scope=pensionAssetScope()){const model=pensionAssetModel(scope,'assetClass'),base=Math.max(0,model.cost),rows=model.segments.map(x=>({name:x.name,key:x.key,value:x.value,cost:x.cost,profit:x.profit,rate:x.cost?x.profit/x.cost*100:0,contribution:base?x.profit/base*100:0,pct:x.pct,color:x.color}));return{scope,totalRate:model.rate,totalProfit:model.profit,totalCost:model.cost,rows,ranked:[...rows].sort((a,b)=>Math.abs(b.contribution)-Math.abs(a.contribution))}}
function pensionHoldingById(id){return pensionStore().holdings.find(h=>h.id===id)||null}

