'use strict';
function sourceArchiveRecords(){return state.sourceArchives?.records||[]}
function pensionArchiveKinds(scope='all',type='all'){
 const prefix=scope==='pension'?['pension']:scope==='irp'?['irp']:['pension','irp'],suffix=type==='realized'?['Realized']:type==='income'?['Dividend']:['Realized','Dividend'];return prefix.flatMap(p=>suffix.map(s=>p+s))
}
function pensionArchivePerformanceRows(scope='all'){
 const kinds=new Set(pensionArchiveKinds(scope)),months=new Map();for(const r of sourceArchiveRecords()){if(!kinds.has(r.kind)||!/^\d{4}-\d{2}/.test(String(r.date)))continue;const key=String(r.date).slice(0,7),row=months.get(key)||{key,date:`${key}-01`,label:key.slice(2).replace('-','.'),realized:0,income:0,total:0,cumulativeRealized:0,cumulativeIncome:0,cumulativeTotal:0};if(String(r.kind).endsWith('Realized'))row.realized+=Number(r.amount)||0;else row.income+=Number(r.amount)||0;row.total=row.realized+row.income;months.set(key,row)}let realized=0,income=0;return [...months.values()].sort((a,b)=>a.date.localeCompare(b.date)).map(row=>{realized+=row.realized;income+=row.income;return{...row,cumulativeRealized:realized,cumulativeIncome:income,cumulativeTotal:realized+income}})
}
function pensionArchivePerformanceSummary(scope='all'){
 const rows=pensionArchivePerformanceRows(scope),last=rows.at(-1)||{cumulativeRealized:0,cumulativeIncome:0,cumulativeTotal:0};return{scope,rows,count:sourceArchiveRecords().filter(r=>pensionArchiveKinds(scope).includes(r.kind)).length,realized:last.cumulativeRealized,income:last.cumulativeIncome,total:last.cumulativeTotal}
}
function pensionArchiveIncomeRecords(scope='all'){
 const kinds=new Set(pensionArchiveKinds(scope,'income'));return sourceArchiveRecords().filter(r=>kinds.has(r.kind)&&/^\d{4}-\d{2}/.test(String(r.date))&&(Number(r.amount)||0)>0).map(r=>({id:r.id,accountId:'',holdingId:'',accountKind:String(r.kind).startsWith('irp')?'irp':'pension',type:'dividend',date:r.date,amount:Number(r.amount)||0,label:r.label,source:'source-archive'}))
}
function pensionArchiveTransactionRows(scope='all'){
 const kinds=new Set(pensionArchiveKinds(scope));return sourceArchiveRecords().filter(r=>kinds.has(r.kind)&&/^\d{4}-\d{2}/.test(String(r.date))).map(r=>{const kind=String(r.kind||''),accountKind=kind.startsWith('irp')?'irp':'pension',income=kind.endsWith('Dividend');return{id:r.id,archive:true,readOnly:true,source:'source-archive',accountKind,type:income?'dividend':'realized',date:String(r.date),amount:Number(r.amount)||0,label:String(r.label||''),note:String(r.note||''),meta:r.meta||{}}}).sort((a,b)=>String(b.date).localeCompare(String(a.date))||String(b.id).localeCompare(String(a.id)))
}
function openPensionArchiveRecord(id){const r=sourceArchiveRecords().find(x=>String(x.id)===String(id));if(!r)return toast('과거자료를 찾지 못했습니다.');const kind=String(r.kind||''),income=kind.endsWith('Dividend'),account=kind.startsWith('irp')?'IRP':'연금저축';$('#sheetEyebrow').textContent=`${account} · 과거자료`;$('#sheetTitle').textContent=income?'배당':'실현손익';$('#sheetBody').innerHTML=`<div class="profitbox"><div class="metric"><span>금액</span><strong class="${Number(r.amount)<0?'negative':'positive'}">${income?won(r.amount):signed(r.amount)}</strong></div><div class="metric"><span>기준일</span><strong>${formatDate(r.date)}</strong></div></div><div class="sheetrows"><div class="sheetrow"><span>계좌</span><strong>${account}</strong></div><div class="sheetrow"><span>원본 구분</span><strong>${escapeHtml(r.label||(income?'배당':'실현손익'))}</strong></div><div class="sheetrow"><span>저장 상태</span><strong>원본 확정 · 읽기 전용</strong></div></div><div class="source-note">보내주신 증권사 과거 화면에서 옮긴 확정자료입니다. 현재 잔고·평단·거래 가능 현금에는 다시 가산하지 않습니다.</div>`;openSheet('#detailSheet')}
function openSourceArchiveHub(){const rows=sourceArchiveRecords(),groups=new Map();for(const r of rows){const key=r.kind||'note',g=groups.get(key)||{kind:key,count:0,total:0};g.count++;g.total+=Number(r.amount)||0;groups.set(key,g)}const labels={pensionRealized:'개인연금 실현손익',irpRealized:'IRP 실현손익',pensionDividend:'개인연금 배당',irpDividend:'IRP 배당',loanInterest:'대출이자 검산',loanFee:'중도상환 수수료',cashFlow:'현금흐름 검산'};$('#sheetEyebrow').textContent='초기자료 · 검산';$('#sheetTitle').textContent=`원본 대조 ${rows.length}건`;$('#sheetBody').innerHTML=`<div class="source-note">이 화면은 사진 원본과 계산값을 대조하는 읽기 전용 자료입니다. KIS 체결·권리 및 실제 원장 합계에는 중복 가산하지 않습니다.</div><div class="sheetrows">${[...groups.values()].map(g=>`<div class="sheetrow"><span>${escapeHtml(labels[g.kind]||g.kind)}<small style="display:block">${g.count}건</small></span><strong>${g.kind==='cashFlow'?won(g.total):signed(g.total)}</strong></div>`).join('')}</div>`;openSheet('#detailSheet')}
