'use strict';
const V04_RELEASE_VERSION='v0.4';
const V04_BACKUP_DB='asset-os-v04-backup';
const V04_BACKUP_STORE='handles';
const V04_PHONE_HANDLE_KEY='phone-backup-dir';
const V04_DRIVE_FOLDER_NAME='Asset OS Backup';
const V04_DAILY_KEEP_DAYS=30;
const V04_AUTO_DELAY_MS=60000;
let v04AutoTimer=0,v04BackupBusy=false,v04GateReady=false;

function v04BackupSettings(){
 state.settings=state.settings||{};
 const base={phoneEnabled:false,driveEnabled:false,driveFolderId:'',lastPhoneBackupAt:'',lastDriveBackupAt:'',lastReleaseVersion:'',manualKeepCount:0};
 state.settings.v04Backup={...base,...(state.settings.v04Backup||{})};
 return state.settings.v04Backup;
}
function v04DateCode(d=new Date()){return `${String(d.getFullYear()).slice(-2)}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`}
function v04SafeVersion(v){return String(v||V04_RELEASE_VERSION).replace(/[^0-9A-Za-z._-]/g,'')||V04_RELEASE_VERSION}
function v04BackupName({date=new Date(),version=V04_RELEASE_VERSION,tag=''}={}){return `AssetOS_${v04DateCode(date)}_${v04SafeVersion(version)}${tag?`_${tag}`:''}.zip`}
function v04ZipBlob(){return new Blob([createBackupZipBytes()],{type:'application/zip'})}
function v04Iso(){return new Date().toISOString()}
function v04RuntimeStatusText(){const s=v04BackupSettings();return `휴대폰 ${s.phoneEnabled?'연결됨':'미연결'} · Drive ${s.driveEnabled?'연결됨':'미연결'}`}

function v04OpenDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(V04_BACKUP_DB,1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(V04_BACKUP_STORE))req.result.createObjectStore(V04_BACKUP_STORE)};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error||new Error('IndexedDB 열기 실패'))})}
async function v04IdbGet(key){const db=await v04OpenDb();try{return await new Promise((resolve,reject)=>{const tx=db.transaction(V04_BACKUP_STORE,'readonly'),r=tx.objectStore(V04_BACKUP_STORE).get(key);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})}finally{db.close()}}
async function v04IdbSet(key,value){const db=await v04OpenDb();try{await new Promise((resolve,reject)=>{const tx=db.transaction(V04_BACKUP_STORE,'readwrite');tx.objectStore(V04_BACKUP_STORE).put(value,key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}finally{db.close()}}
async function v04PhonePermission(handle,request=false){if(!handle)return'denied';const opts={mode:'readwrite'};if(typeof handle.queryPermission==='function'){const q=await handle.queryPermission(opts);if(q==='granted'||!request)return q}if(request&&typeof handle.requestPermission==='function')return handle.requestPermission(opts);return'prompt'}
async function v04ChoosePhoneFolder(){
 if(typeof window.showDirectoryPicker!=='function'||!window.isSecureContext){showNotice('휴대폰 폴더 고정 저장을 지원하지 않습니다.','현재 브라우저에서는 폴더 권한을 고정할 수 없습니다. ZIP 일반 저장은 계속 사용할 수 있습니다.');return false}
 try{const h=await window.showDirectoryPicker({id:'asset-os-backup',mode:'readwrite',startIn:'downloads'});if(await v04PhonePermission(h,true)!=='granted')throw new Error('폴더 쓰기 권한이 필요합니다.');await v04IdbSet(V04_PHONE_HANDLE_KEY,h);const s=v04BackupSettings();s.phoneEnabled=true;persist(false);toast('휴대폰 백업 폴더를 고정했습니다.');return true}catch(e){if(e?.name!=='AbortError')showNotice('폴더 연결 실패',String(e?.message||e));return false}
}
async function v04PhoneHandle({request=false}={}){try{const h=await v04IdbGet(V04_PHONE_HANDLE_KEY);if(!h)return null;return await v04PhonePermission(h,request)==='granted'?h:null}catch{return null}}
function v04ParseBackupName(name){const m=/^AssetOS_(\d{6})_(v[0-9A-Za-z._-]+?)(?:_(pre|keep))?\.zip$/i.exec(String(name||''));if(!m)return null;const yy=Number(m[1].slice(0,2)),mm=Number(m[1].slice(2,4)),dd=Number(m[1].slice(4,6)),year=2000+yy,date=new Date(year,mm-1,dd);if(date.getFullYear()!==year||date.getMonth()!==mm-1||date.getDate()!==dd)return null;return{date,month:`${year}-${String(mm).padStart(2,'0')}`,tag:m[3]||'',name:String(name)}}
function v04RetentionPlan(rows){const now=new Date(),cutoff=new Date(now.getFullYear(),now.getMonth(),now.getDate()-V04_DAILY_KEEP_DAYS),old=rows.filter(x=>x.info&&!x.info.tag&&x.info.date<cutoff),keep=new Set(rows.filter(x=>x.info?.tag).map(x=>x.name));for(const x of rows.filter(x=>x.info&&!x.info.tag&&x.info.date>=cutoff))keep.add(x.name);const byMonth=new Map();for(const x of old){const prev=byMonth.get(x.info.month);if(!prev||prev.info.date<x.info.date)byMonth.set(x.info.month,x)}for(const x of byMonth.values())keep.add(x.name);return{keep,remove:rows.filter(x=>x.info&&!keep.has(x.name)).map(x=>x.name)}}
async function v04CleanupPhone(handle){try{const rows=[];for await(const [name,entry] of handle.entries())if(entry.kind==='file'){const info=v04ParseBackupName(name);if(info)rows.push({name,info})}const plan=v04RetentionPlan(rows);for(const name of plan.remove)await handle.removeEntry(name);return plan}catch{return{keep:new Set(),remove:[]}}}
async function v04WritePhone({tag='',version=V04_RELEASE_VERSION,silent=false}={}){
 const h=await v04PhoneHandle();if(!h){if(!silent)showNotice('휴대폰 백업 폴더 연결이 필요합니다.','백업·복원에서 휴대폰 폴더를 한 번 지정해 주세요.');return false}
 const name=v04BackupName({version,tag});try{const f=await h.getFileHandle(name,{create:true}),w=await f.createWritable();await w.write(v04ZipBlob());await w.close();await v04CleanupPhone(h);const s=v04BackupSettings();s.phoneEnabled=true;s.lastPhoneBackupAt=v04Iso();v04PersistMeta();if(!silent)toast(`휴대폰 백업 완료: ${name}`);return true}catch(e){if(!silent)showNotice('휴대폰 백업 실패',String(e?.message||e));return false}
}

function v04DriveToken(){return String(assetSupabaseSession?.provider_token||'')}
async function v04DriveJson(url,options={}){const token=v04DriveToken();if(!token)return{ok:false,status:401,error:'DRIVE_TOKEN_REQUIRED'};const r=await fetch(url,{...options,headers:{authorization:`Bearer ${token}`,...(options.headers||{})}});let data=null;const text=await r.text();try{data=text?JSON.parse(text):null}catch{data=text}return r.ok?{ok:true,status:r.status,data}:{ok:false,status:r.status,error:data?.error?.message||data?.error||text||`HTTP_${r.status}`}}
async function v04ConnectDrive(){
 if(!assetSupabaseClient&&!(await initSupabaseCloud()))return false;
 try{const {error}=await assetSupabaseClient.auth.signInWithOAuth({provider:'google',options:{redirectTo:SUPABASE_REDIRECT_URL,scopes:'https://www.googleapis.com/auth/drive.file',queryParams:{access_type:'offline',prompt:'consent'}}});if(error)throw error;return true}catch(e){showNotice('Google Drive 연결 실패',String(e?.message||e));return false}
}
async function v04DriveListFolderByName(){const q=encodeURIComponent(`name='${V04_DRIVE_FOLDER_NAME.replaceAll("'","\\'")}' and mimeType='application/vnd.google-apps.folder' and trashed=false`),url=`https://www.googleapis.com/drive/v3/files?q=${q}&spaces=drive&fields=files(id,name)&pageSize=20`;return v04DriveJson(url)}
async function v04EnsureDriveFolder(){const s=v04BackupSettings();if(s.driveFolderId)return s.driveFolderId;let r=await v04DriveListFolderByName();if(!r.ok)return'';let id=r.data?.files?.[0]?.id||'';if(!id){r=await v04DriveJson('https://www.googleapis.com/drive/v3/files?fields=id,name',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:V04_DRIVE_FOLDER_NAME,mimeType:'application/vnd.google-apps.folder'})});if(!r.ok)return'';id=r.data?.id||''}if(id){s.driveFolderId=id;s.driveEnabled=true;persist(false)}return id}
async function v04DriveListBackups(folderId){const q=encodeURIComponent(`'${folderId}' in parents and trashed=false`),url=`https://www.googleapis.com/drive/v3/files?q=${q}&spaces=drive&fields=files(id,name,createdTime,modifiedTime)&pageSize=1000`;const r=await v04DriveJson(url);return r.ok?(r.data?.files||[]):[]}
async function v04DriveCreateFile(folderId,name,blob){const boundary='assetos'+Date.now().toString(36),meta=JSON.stringify({name,parents:[folderId]}),body=new Blob([`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${meta}\r\n--${boundary}\r\nContent-Type: application/zip\r\n\r\n`,blob,`\r\n--${boundary}--`]);return v04DriveJson('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name',{method:'POST',headers:{'content-type':`multipart/related; boundary=${boundary}`},body})}
async function v04DriveUpdateFile(id,blob){return v04DriveJson(`https://www.googleapis.com/upload/drive/v3/files/${encodeURIComponent(id)}?uploadType=media&fields=id,name,modifiedTime`,{method:'PATCH',headers:{'content-type':'application/zip'},body:blob})}
async function v04CleanupDrive(folderId,files=null){const rows=(files||await v04DriveListBackups(folderId)).map(f=>({name:f.name,id:f.id,info:v04ParseBackupName(f.name)})).filter(x=>x.info),plan=v04RetentionPlan(rows);for(const x of rows)if(plan.remove.includes(x.name))await v04DriveJson(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(x.id)}`,{method:'DELETE'});return plan}
async function v04WriteDrive({tag='',version=V04_RELEASE_VERSION,silent=false}={}){
 if(v04BackupBusy)return false;v04BackupBusy=true;try{if(!cloudUser()){if(!silent)showNotice('Google 로그인이 필요합니다.','Asset OS Google 로그인 후 Drive를 연결해 주세요.');return false}if(!v04DriveToken()){if(!silent)showNotice('Google Drive 권한 재연결이 필요합니다.','Drive 자동백업 권한은 별도입니다. Drive 연결을 한 번 눌러 권한을 허용해 주세요.');return false}const folderId=await v04EnsureDriveFolder();if(!folderId){if(!silent)showNotice('Drive 폴더 확인 실패','Google Drive 권한을 다시 연결해 주세요.');return false}const name=v04BackupName({version,tag}),files=await v04DriveListBackups(folderId),existing=files.find(x=>x.name===name),blob=v04ZipBlob(),r=existing?await v04DriveUpdateFile(existing.id,blob):await v04DriveCreateFile(folderId,name,blob);if(!r.ok){if(!silent)showNotice('Drive 백업 실패',String(r.error||'Google Drive 업로드 오류'));return false}await v04CleanupDrive(folderId,existing?files:[...files,{id:r.data?.id,name}]);const s=v04BackupSettings();s.driveEnabled=true;s.lastDriveBackupAt=v04Iso();v04PersistMeta();if(!silent)toast(`Drive 백업 완료: ${name}`);return true}finally{v04BackupBusy=false}
}
async function v04CreatePreUpgradeBackups(){const s=v04BackupSettings();if(s.lastReleaseVersion===V04_RELEASE_VERSION)return;const previous=s.lastReleaseVersion||'v0.3';if(s.phoneEnabled)await v04WritePhone({tag:'pre',version:previous,silent:true});if(s.driveEnabled)await v04WriteDrive({tag:'pre',version:previous,silent:true});s.lastReleaseVersion=V04_RELEASE_VERSION;persist(false)}
function v04QueueAutoBackup(){clearTimeout(v04AutoTimer);v04AutoTimer=setTimeout(async()=>{const s=v04BackupSettings();if(s.phoneEnabled)await v04WritePhone({silent:true});if(s.driveEnabled)await v04WriteDrive({silent:true})},V04_AUTO_DELAY_MS)}

function v04PatchStoredEnvelopeVersion(){try{const raw=localStorage.getItem(KEY),env=raw?JSON.parse(raw):null;if(env?.data){env.appVersion=V04_RELEASE_VERSION;localStorage.setItem(KEY,JSON.stringify(env));return true}}catch{}return false}
const v04OriginalBackupPayload=typeof backupPayload==='function'?backupPayload:null;
if(v04OriginalBackupPayload){backupPayload=function(){const p=v04OriginalBackupPayload();p.appVersion=V04_RELEASE_VERSION;return p}}
const v04OriginalPersist=typeof persist==='function'?persist:null;
function v04PersistMeta(){if(!v04OriginalPersist)return false;const ok=v04OriginalPersist(false);if(ok)v04PatchStoredEnvelopeVersion();return ok}
if(v04OriginalPersist){persist=function(...args){const ok=v04OriginalPersist(...args);if(ok){v04PatchStoredEnvelopeVersion();if(v04GateReady)v04QueueAutoBackup()}return ok}}

const v04OriginalOpenBackupHub=typeof openBackupHub==='function'?openBackupHub:null;
openBackupHub=function(){const s=v04BackupSettings(),size=new Blob([JSON.stringify(backupPayload())]).size,phoneApi=typeof window.showDirectoryPicker==='function'&&window.isSecureContext;$('#sheetEyebrow').textContent='데이터 보호';$('#sheetTitle').textContent='백업·복원';$('#sheetBody').innerHTML=`<div class="backup-grid"><button class="backup-action primary" data-v04-phone-connect><strong>휴대폰 백업 폴더 ${s.phoneEnabled?'변경':'지정'}</strong><small>${phoneApi?'한 번 지정하면 권한이 유지되는 동안 같은 폴더에 저장합니다.':'이 브라우저는 고정 폴더 저장을 지원하지 않을 수 있습니다.'}</small></button><button class="backup-action" data-v04-phone-save><strong>휴대폰 ZIP 지금 저장</strong><small>${s.lastPhoneBackupAt?`마지막 ${formatDateTime(s.lastPhoneBackupAt)}`:'아직 저장하지 않음'} · ${v04BackupName()}</small></button><button class="backup-action" data-v04-drive-connect><strong>Google Drive ${s.driveEnabled?'재연결':'연결'}</strong><small>Drive의 “${V04_DRIVE_FOLDER_NAME}” 폴더를 고정해서 사용합니다.</small></button><button class="backup-action" data-v04-drive-save><strong>Drive ZIP 지금 저장</strong><small>${s.lastDriveBackupAt?`마지막 ${formatDateTime(s.lastDriveBackupAt)}`:'아직 저장하지 않음'} · 같은 날짜 파일은 갱신</small></button><button class="backup-action" data-v04-keep><strong>수동 영구보관 ZIP</strong><small>정리 대상에서 제외되는 _keep 백업을 만듭니다.</small></button><button class="backup-action" data-backup-restore><strong>ZIP / JSON 복원</strong><small>schema ${SCHEMA_VERSION} 포함 이전 지원 형식을 검증한 뒤 복원합니다.</small></button></div><div class="backup-status-note">현재 원본 약 ${Math.max(1,Math.round(size/1024))}KB · ${v04RuntimeStatusText()}<br>최근 30일은 일별 보관, 그 이전은 월 1개, _pre / _keep은 유지합니다.</div>`;openSheet('#detailSheet');setTimeout(()=>{$('[data-v04-phone-connect]').onclick=async()=>{if(await v04ChoosePhoneFolder()){await v04CreatePreUpgradeBackups();openBackupHub()}};$('[data-v04-phone-save]').onclick=()=>v04WritePhone();$('[data-v04-drive-connect]').onclick=v04ConnectDrive;$('[data-v04-drive-save]').onclick=()=>v04WriteDrive();$('[data-v04-keep]').onclick=async()=>{const a=await v04WritePhone({tag:'keep'}),b=await v04WriteDrive({tag:'keep'});if(a||b){s.manualKeepCount=(Number(s.manualKeepCount)||0)+1;persist(false)}};$('[data-backup-restore]').onclick=()=>$('#backupInput').click()},0)};

let v04InstallPrompt=null;
function v04EnsureInstallButton(){
 const list=document.querySelector('#profileSheet .menulist');if(!list||$('#installAssetOSV04'))return;
 const b=document.createElement('button');b.id='installAssetOSV04';b.className='menurow';b.innerHTML='<span class="menuico">⇩</span><span class="menucopy"><strong>Asset OS 앱 설치</strong><small id="installAssetOSV04Status">설치 가능 여부 확인 중</small></span><span class="menugo">›</span>';
 b.onclick=async()=>{if(v04InstallPrompt){const p=v04InstallPrompt;v04InstallPrompt=null;await p.prompt();const choice=await p.userChoice.catch(()=>null);const status=$('#installAssetOSV04Status');if(status)status.textContent=choice?.outcome==='accepted'?'설치 요청 완료':'설치 취소됨';return}showNotice('앱 설치 메뉴를 확인해 주세요.','Chrome 메뉴에서 “앱 설치” 또는 “홈 화면에 추가”를 선택해 주세요. 설치 조건이 충족되면 이 메뉴에서도 바로 설치할 수 있습니다.')};
 list.appendChild(b)
}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();v04InstallPrompt=e;v04EnsureInstallButton();const s=$('#installAssetOSV04Status');if(s)s.textContent='지금 설치 가능'});
window.addEventListener('appinstalled',()=>{v04InstallPrompt=null;const s=$('#installAssetOSV04Status');if(s)s.textContent='설치됨'});

function v04PatchVersionLabels(){if(window.__assetOS)window.__assetOS.version=V04_RELEASE_VERSION;document.title='Asset OS v0.4';$$('.appversion').forEach(x=>x.textContent=V04_RELEASE_VERSION);$$('.statuschip').forEach(x=>{if(/v0\.3/i.test(x.textContent))x.textContent='v0.4 LIVE'});$$('.diagnostic-value').forEach(x=>{if(/^v0\.3 LIVE$/i.test(String(x.textContent||'').trim()))x.textContent='v0.4 LIVE'})}
function v04InjectPwa(){if(!document.querySelector('link[rel="manifest"]')){const l=document.createElement('link');l.rel='manifest';l.href='./manifest.webmanifest';document.head.appendChild(l)}if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}),{once:true})}
function v04GateElement(){let gate=$('#assetAuthGateV04');if(gate)return gate;gate=document.createElement('div');gate.id='assetAuthGateV04';gate.innerHTML='<div class="asset-auth-card"><strong>ASSET OS</strong><span>Google 로그인 확인 중…</span><button type="button" hidden>Google로 로그인</button><small>로그인 후 Supabase 동기화를 확인한 뒤 자산 화면을 엽니다.</small></div>';document.body.appendChild(gate);return gate}
function v04GateCss(){if($('#assetV04Style'))return;const s=document.createElement('style');s.id='assetV04Style';s.textContent='html.asset-auth-pending .app{visibility:hidden!important;pointer-events:none!important}#assetAuthGateV04{position:fixed;inset:0;z-index:99999;background:var(--bg,#eef3fb);display:flex;align-items:center;justify-content:center;padding:24px}#assetAuthGateV04[hidden]{display:none}.asset-auth-card{width:min(360px,100%);background:var(--card,#fff);border:1px solid rgba(0,0,0,.08);border-radius:24px;padding:28px 22px;display:grid;gap:12px;text-align:center;box-shadow:0 16px 48px rgba(0,0,0,.08)}.asset-auth-card strong{font-size:24px}.asset-auth-card span,.asset-auth-card small{color:var(--muted,#687386)}.asset-auth-card button{border:0;border-radius:14px;padding:14px 16px;font-weight:700;background:#2f6fed;color:white;font-size:15px}';document.head.appendChild(s)}
async function v04StartGate(){v04GateCss();const gate=v04GateElement(),status=gate.querySelector('span'),button=gate.querySelector('button');document.documentElement.classList.add('asset-auth-pending');button.onclick=()=>signInAssetGoogle();let ok=false;try{ok=await initSupabaseCloud()}catch{}const user=ok?cloudUser():null;if(!user){status.textContent=ok?'Google 로그인이 필요합니다.':'클라우드 연결을 확인해 주세요.';button.hidden=!ok;return}status.textContent='동기화 확인 완료';await v04CreatePreUpgradeBackups();v04GateReady=true;gate.hidden=true;document.documentElement.classList.remove('asset-auth-pending');v04QueueAutoBackup()}

v04InjectPwa();v04PatchVersionLabels();v04EnsureInstallButton();v04GateCss();document.documentElement.classList.add('asset-auth-pending');if(document.readyState==='complete')v04StartGate();else window.addEventListener('load',v04StartGate,{once:true});
