'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
function env(){const c=vm.createContext({console,Date,Set,Map,Intl,TextEncoder,state:{accounts:[],brokerKis:{rights:[]}},pensionAccount:id=>({id,kind:'pension',name:'연금'}),pensionHoldingById:()=>null,pensionSnapshotRows:()=>[],pensionAssetMetrics:()=>({cost:1000}),localYmd:()=> '2026-09-19',pensionTransactions:()=>[],integratedLedger:()=>[],pensionArchiveTransactionRows:()=>[]});for(const f of ['broker-kis.js','pension-assets.js','export-csv.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',f),'utf8'),c);vm.runInContext('pensionHoldingById=()=>null',c);return c}
test('partial itemization retains historical month remainder and does not subtract interest',()=>{const c=env();c.details=[{id:'d',accountId:'p',type:'distribution',date:'2025-09-17',amount:30},{id:'i',accountId:'p',type:'interest',date:'2025-09-18',amount:10}];c.archive=[{id:'a',accountKind:'pension',type:'dividend',date:'2025-09-01',amount:100}];const before=JSON.stringify(c.archive),rows=vm.runInContext('pensionReconcileIncome(details,archive)',c);assert.equal(rows.reduce((s,x)=>s+x.amount,0),110);assert.equal(rows.find(x=>x.id==='a').amount,70);assert.equal(JSON.stringify(c.archive),before)});
test('one confirmed broker payment matches only one manual payment',()=>{const c=env();const payment={accountId:'p',productCode:'489250',type:'distribution',date:'2026-09-17',amount:11808,tax:0};c.details=[{...payment,id:'b',source:'kis-right',brokerRight:true},{...payment,id:'m',source:'transaction'},{...payment,id:'m2',source:'transaction'}];const rows=vm.runInContext('pensionReconcileIncome(details,[])',c);assert.equal(rows.length,2);assert.equal(rows.reduce((s,x)=>s+x.amount,0),23616)});
test('missing historical principal is not a zero percent return',()=>{const c=env();assert.equal(vm.runInContext("pensionIncomeRate('all',100,'2025','year')",c),null)});
test('CSV includes the same broker distribution and archive remainder as history',()=>{const c=env();c.income=[{id:'b',source:'kis-right',brokerRight:true,accountId:'p',type:'distribution',date:'2026-09-17',productName:'나스닥 ETF',amount:85000,tax:15000},{id:'a',archive:true,accountKind:'pension',type:'dividend',date:'2025-01-01',amount:70,originalAmount:100,reconciledAmount:30}];vm.runInContext('pensionIncomeRecords=()=>income;brokerKisVisibleOrders=()=>[]',c);const csv=vm.runInContext("excelCsvEntries().find(x=>x.name==='연금거래.csv').text",c);assert.match(csv,/나스닥 ETF/);assert.match(csv,/85000/);assert.match(csv,/100,30/)});
test('explicit liquidation must not become a distribution based on ETF name',()=>{const c=env();assert.equal(vm.runInContext("brokerKisRightIncomeType({productName:'KODEX ETF',rightTypeName:'청산대금'})",c),'other_right');assert.equal(vm.runInContext("brokerKisRightIncomeType({productName:'KODEX ETF',rightTypeName:'분배금'})",c),'distribution')});
test('rights metadata refresh reclassifies an unchanged amount without duplicating cash',()=>{const c=env();c.row={rightTypeCode:'32',baseDate:'2026-09-01',cashPaymentDate:'2026-09-17',productCode:'489250',productName:'KODEX ETF',amount:11808,tax:0};vm.runInContext("var store=brokerKisEmptyStore();brokerKisImportRights(store,[row],'pension','p','2026-09-19T01:00:00Z')",c);const result=vm.runInContext("brokerKisImportRights(store,[{...row,rightTypeName:'청산대금'}],'pension','p','2026-09-19T02:00:00Z')",c);assert.equal(result.updated,1);assert.equal(vm.runInContext('store.rights.length',c),1);assert.equal(vm.runInContext("brokerKisRightIncomeRecords(store)[0].type",c),'other_right');assert.equal(vm.runInContext("brokerKisRightIncomeRecords(store)[0].classificationBasis",c),'event-description');vm.runInContext("brokerKisImportRights(store,[{...row,amount:12000}],'pension','p','2026-09-19T03:00:00Z')",c);assert.equal(vm.runInContext('store.rights[0].rightTypeName',c),'청산대금');assert.equal(vm.runInContext('store.rights[0].amount',c),12000)});
test('unknown code never provides confirmed classification and backup keeps supplied event',()=>{const c=env();assert.equal(vm.runInContext("brokerKisRightClassificationBasis({rightTypeCode:'32',productName:'KODEX ETF'})",c),'name-inferred');assert.equal(vm.runInContext("brokerKisRightClassificationBasis({rightTypeName:'정체불명',productName:'KODEX ETF'})",c),'unverified');assert.equal(vm.runInContext("brokerKisRightClassificationBasis({instrumentType:'etf'})",c),'instrument-inferred');assert.equal(vm.runInContext("brokerKisNormalizeRight({eventType:'분배금'}).rightTypeName",c),'분배금')});
test('income card resolves original holding name after broker view replaces holdings',()=>{const c=env();vm.runInContext(fs.readFileSync(path.join(__dirname,'..','pension-pages.js'),'utf8'),c);Object.assign(c,{pensionStore:()=>({holdings:[{id:'original',name:'나스닥100 원본종목'}]}),pensionIncomeSummary:()=>({records:[{holdingId:'original',amount:100}],total:100,year:'2026',yearTotal:100,yieldRate:null}),escapeHtml:String,won:String,displayWon:String,amountClass:()=>''});assert.match(vm.runInContext("pensionIncomeCard('all')",c),/나스닥100 원본종목/)});
