'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.join(__dirname,'..');
function env(){const storage=new Map(),c=vm.createContext({console,Date,Set,Map,URL,Blob,TextEncoder,TextDecoder,Uint8Array,DataView,ArrayBuffer,Intl,Math,JSON,Number,String,Boolean,Object,RegExp,Promise,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},document:{querySelector:()=>null,querySelectorAll:()=>[],documentElement:{dataset:{}},body:{dataset:{}}},window:{addEventListener:()=>{}},navigator:{},location:{search:'?qa=1',hash:''},setTimeout:()=>0,clearTimeout:()=>{}});for(const f of ['core-config.js','broker-kis.js','data-defaults.js','integrated-ledger-engine.js','integrated-schedule-engine.js','integrated-finance-engine.js','store-state.js','core-accessors.js','pension-contributions.js','pension-ledger.js','pension-assets.js','isa-validation.js','isa-ledger.js','isa-registration.js','isa-maturity-policy.js','integrated-forms.js','integrated-finance-ui.js','insurance.js','backup.js','export-csv.js','integrated-pages.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),c,{filename:f});const bytes=fs.readFileSync(path.join(root,'qa-evidence/manual-30-year-backup.zip')),offset=30+bytes.readUInt16LE(26)+bytes.readUInt16LE(28);c.fixture=JSON.parse(require('node:zlib').inflateRawSync(bytes.subarray(offset,offset+bytes.readUInt32LE(18))).toString()).data;vm.runInContext('state=normalizeState(fixture)',c);return c}
const run=(c,s)=>vm.runInContext(s,c);
test('30-year backup pension valuation equals integrated valuation without verification flag',()=>{const c=env();assert.equal(run(c,"pensionAssetMetrics('all').value"),108022400);assert.equal(run(c,'integratedFinancialModel().pension+integratedFinancialModel().irp'),108022400);assert.equal(run(c,'integratedFinancialModel().netAssets'),799612010)});
test('30-year linked contributions appear once in views and CSV without mutating ledger',()=>{const c=env(),before=run(c,'JSON.stringify(state)');assert.equal(run(c,"pensionVisibleTransactionRows().filter(t=>t.linkedContribution).length"),720);assert.equal(run(c,"excelCsvEntries().find(x=>x.name==='ISA거래.csv').text.split('\\r\\n').filter(Boolean).length"),37);assert.equal(run(c,"excelCsvEntries().find(x=>x.name==='연금거래.csv').text.split('\\r\\n').filter(Boolean).length"),733);assert.equal(run(c,'JSON.stringify(state)'),before)});
test('insurance actual payments use ledger only and retain separate historic declared totals',()=>{const c=env();c.p={id:'new',premium:10000,contractDate:'2031-01-01',paymentEndDate:'2060-12-31',status:'active'};assert.equal(run(c,'insurancePremiumSummary(p).paid'),0);run(c,"state.financeSchedules.items.push({id:'new-s',kind:'insurance',productId:'new'});state.integrated.ledger.push({id:'ip',type:'expense',date:'2034-02-01',amount:10000,fromAccountId:'cash-main',meta:{scheduleId:'new-s'}})");assert.equal(run(c,'insurancePremiumSummary(p).paid'),10000);c.p.status='ended';assert.equal(run(c,'insurancePremiumSummary(p).remaining'),0)});
test('partial and cross-month refunds restore cash, reduce refund-month spending and cap total',()=>{const c=env();run(c,"state.integrated.ledger.push({id:'purchase',type:'expense',date:'2060-10-01',amount:10000,fromAccountId:'cash-main',category:'QA 환불',fixed:false})");const cash=run(c,"integratedReplay().assets['cash-main']"),spend=run(c,"integratedSpendingAnalysis('2060-11').total");assert.equal(run(c,"recordIntegratedRefund('purchase','2060-11-02',3000).ok"),true);assert.equal(run(c,"recordIntegratedRefund('purchase','2060-12-02',7000).ok"),true);assert.equal(run(c,"recordIntegratedRefund('purchase','2060-12-03',1).ok"),false);assert.equal(run(c,"integratedReplay().assets['cash-main']"),cash+10000);assert.equal(run(c,"integratedSpendingAnalysis('2060-11').total"),spend-3000);assert.equal(run(c,"state.integrated.ledger.find(t=>t.id==='purchase').amount"),10000);run(c,"state.integrated.ledger=state.integrated.ledger.filter(t=>t.id!=='purchase')");assert.ok(run(c,"integratedIssues().some(x=>x.includes('환불 원거래'))"))});
test('an unrelated KIS partial-refresh warning never blocks a valid cash transaction',()=>{const c=env();run(c,"state.brokerKis.connections.pension={accountId:'qa-pension',lastError:'PARTIAL_REFRESH'}");assert.ok(run(c,"systemIntegrityIssues().some(x=>x.includes('한투 갱신이 부분 완료'))"));assert.equal(run(c,"integratedValidateCandidate({id:'valid-cash-expense',date:'2060-12-31',type:'expense',amount:1,fromAccountId:'cash-main'})"),'');assert.deepEqual(JSON.parse(run(c,"JSON.stringify(integratedCandidateIssues(state.integrated))")),[])});
test('ISA closure transfers once, keeps archive contributions and restores consistently',()=>{const c=env();c.id=run(c,'state.accounts[0].id');const before=run(c,'integratedFinancialModel().netAssets');assert.equal(run(c,"recordIsaLifecycle(id,{action:'close',date:'2033-12-31',settlement:10800000,tax:0}).ok"),true);assert.equal(run(c,'integratedFinancialModel().netAssets'),before);assert.equal(run(c,'centralIsaReplayRows(state.accounts[0],true).length'),36);assert.equal(run(c,'archivedIsaTransactionRows(state.accounts[0]).length'),36);assert.equal(run(c,"recordIsaLifecycle(id,{action:'close',date:'2033-12-31',settlement:10800000,tax:0}).ok"),false);run(c,'state=normalizeState(JSON.parse(JSON.stringify(state)))');assert.equal(run(c,'integratedFinancialModel().netAssets'),before)});
test('ISA extension keeps history and pension transfer preserves net assets',()=>{const c=env();c.id=run(c,'state.accounts[0].id');assert.equal(run(c,"recordIsaLifecycle(id,{action:'extend',date:'2033-12-31',maturityAt:'2036-12-31'}).ok"),true);const before=run(c,'integratedFinancialModel().netAssets');c.target=run(c,"pensionStore().accounts.find(a=>a.kind==='pension').id");const result=run(c,"recordIsaLifecycle(id,{action:'transfer',date:'2036-12-31',settlement:10800000,tax:0,transfer:10000000,targetAccountId:target})");assert.equal(result.ok,true,result.error);assert.equal(run(c,'integratedFinancialModel().netAssets'),before);assert.equal(run(c,"centralPensionContributionRows().filter(t=>t.type==='isaTransfer').length"),1)});

test('refund display stays positive in net spending rows',()=>{const c=env();assert.equal(run(c,"integratedTxAmountMarkup({type:'refund',amount:-1000}).includes('+-')"),false)});

function settlementEnv(){const c=env();c.sheetDirty=false;c.integratedLedgerSearch="";c.FormData=class{constructor(form){this.values=form.values}get(k){return this.values[k]??null}};run(c,"toast=s=>{globalThis.message=s};persist=()=>true;closeSheets=()=>{};render=()=>{};state.financialProducts.items.push({id:'settle-test',name:'QA 정산',type:'deposit',status:'active',startDate:'2031-01-01'});syncFinancialProductStructures(state);state.integrated.ledger.push({id:'settle-principal',type:'externalAssetIn',date:'2035-01-01',amount:1000000,toAccountId:'finance-asset-settle-test',productId:'settle-test'})");return c}
test('early cancellation keeps principal and loss balanced through 2060',()=>{const c=settlementEnv();const before=run(c,'integratedFinancialModel().netAssets');c.form={dataset:{productId:'settle-test'},values:{date:'2036-01-01',received:'950000',reason:'earlyCancel'}};run(c,'saveFinanceSettlement(form)');assert.equal(run(c,'integratedFinancialModel().netAssets'),before-50000);assert.equal(run(c,"financialProduct('settle-test').status"),'ended');assert.equal(run(c,"financeProductBalance(financialProduct('settle-test'))"),0);for(let year=2036;year<=2060;year++)assert.equal(run(c,`integratedReplay(integratedOperationalLedger().filter(t=>t.date<='${year}-12-31')).assets['finance-asset-settle-test']`),0);const count=run(c,'state.integrated.ledger.length');run(c,'saveFinanceSettlement(form)');assert.equal(run(c,'state.integrated.ledger.length'),count)});
test('settlement rejects invalid dates, amounts and later transactions without changes',()=>{for(const values of [{date:'2034-12-31',received:'900000'},{date:'2036-01-01',received:'NaN'},{date:'2036-01-01',received:'-1'},{date:'2036-01-01',received:''},{date:'2061-01-01',received:'900000'}]){const c=settlementEnv(),before=run(c,'JSON.stringify(state)');c.form={dataset:{productId:'settle-test'},values};run(c,'saveFinanceSettlement(form)');assert.equal(run(c,'JSON.stringify(state)'),before,JSON.stringify(values))}});
test('settlement validation failure cannot leave half a settlement',()=>{const c=settlementEnv(),before=run(c,'JSON.stringify(state)');run(c,"integratedValidateCandidate=t=>t.type==='expense'?'QA rejection':''");c.form={dataset:{productId:'settle-test'},values:{date:'2036-01-01',received:'900000'}};run(c,'saveFinanceSettlement(form)');assert.equal(run(c,'JSON.stringify(state)'),before)});

test('actual early repayment fee is an expense and never reduces principal twice',()=>{const c=settlementEnv();run(c,"state.financialProducts.items.push({id:'loan-fee',name:'QA 수수료',type:'loan',status:'active',startDate:'2031-01-01'});syncFinancialProductStructures(state);state.integrated.ledger.push({id:'fee-loan-open',date:'2035-01-01',type:'openingLiability',amount:1000000,liabilityId:'finance-debt-loan-fee'})");const before=run(c,'integratedFinancialModel().netAssets'),cash=run(c,"integratedReplay().assets['cash-main']");c.form={dataset:{productId:'loan-fee',action:'payoff'},values:{date:'2036-01-01',amount:'1000000',source:'tracked',repaymentFee:'10000'}};run(c,'saveFinanceMovement(form)');assert.equal(run(c,"financeProductBalance(financialProduct('loan-fee'))"),0);assert.equal(run(c,'integratedFinancialModel().netAssets'),before-10000);assert.equal(run(c,"integratedReplay().assets['cash-main']"),cash-1010000);assert.equal(run(c,"financialProduct('loan-fee').status"),'ended')});

test('saved-only and proposed policies never silently change historic pension limits',()=>{const c=env();const original=run(c,"pensionSummary('2060').psLimit");run(c,"policyGroup('pension').versions.push({...policy('pension'),id:'draft',userEdited:true,status:'user',effectiveFrom:'2035-01-01',annualTaxCreditLimit:99999999})");assert.equal(run(c,"pensionSummary('2060').psLimit"),original);run(c,"policyGroup('pension').versions.push({...policy('pension'),id:'proposal',status:'proposal',effectiveFrom:'2040-01-01',annualTaxCreditLimit:88888888})");assert.equal(run(c,"pensionSummary('2060').psLimit"),original);run(c,"showDialog=(options,yes)=>yes();persist=()=>true;openPolicyHub=()=>{};render=()=>{};toast=()=>{};applyPolicyVersion('pension','draft')");assert.equal(run(c,"pensionSummary('2060').psLimit"),99999999);for(let year=2035;year<2060;year++)assert.equal(run(c,`pensionSummary('${year}').psLimit`),original);run(c,'state=normalizeState(JSON.parse(JSON.stringify(state)))');assert.equal(run(c,"pensionSummary('2059').psLimit"),original);assert.equal(run(c,"pensionSummary('2060').psLimit"),99999999)});

test('lump-sum insurance records actual cash and refund without monthly schedules',()=>{const c=env();run(c,"state.insurance.policies.push({id:'lump',name:'QA 일시납',status:'active',paymentStyle:'lump',premium:1000000,contractDate:'2040-01-31',paymentEndDate:'2040-01-31',coverages:[]});syncInsuranceSchedule(insurancePolicies().find(p=>p.id==='lump'),true)");assert.equal(run(c,"financeSchedules().some(s=>s.productId==='lump')"),false);const cash=run(c,"integratedReplay().assets['cash-main']");assert.equal(run(c,"recordInsurancePayment('lump',{date:'2040-01-31',amount:1000000,paymentId:'lump-paid'}).ok"),true);assert.equal(run(c,"recordInsurancePayment('lump',{date:'2040-01-31',amount:1000000,paymentId:'lump-paid'}).ok"),false);assert.equal(run(c,"insurancePremiumSummary(insurancePolicies().find(p=>p.id==='lump')).paid"),1000000);assert.equal(run(c,"integratedReplay().assets['cash-main']"),cash-1000000);assert.equal(run(c,"recordIntegratedRefund('lump-paid','2040-02-01',100000).ok"),true);assert.equal(run(c,"insurancePremiumSummary(insurancePolicies().find(p=>p.id==='lump')).paid"),900000);for(let year=2040;year<=2060;year++)assert.equal(run(c,`insurancePremiumSummary(insurancePolicies().find(p=>p.id==='lump'),'${year}-12-31').paid`),900000)});

test('editing an outside insurance expense preserves the original funding path and link',()=>{const c=settlementEnv();run(c,"state.integrated.ledger.push({id:'insurance-edit',date:'2040-01-01',type:'externalExpense',amount:10000,productId:'policy-existing',fixed:true,meta:{insurancePayment:true}})");c.form={dataset:{editId:'insurance-edit'},values:{date:'2040-01-01',uiType:'lifeExpense',amount:'15000',category:'QA 보험료'}};const tx=run(c,'integratedCandidatesFromForm(form)[0]');assert.equal(tx.type,'externalExpense');assert.equal(tx.productId,'policy-existing');assert.equal(tx.fromAccountId,undefined);assert.equal(tx.fixed,true);assert.equal(tx.meta.insurancePayment,true)});

test('monthly detail includes refunds, external expenses, outside contributions and withdrawals',()=>{
 const c=env();run(c,`state.integrated.ledger.push(
 {id:'detail-exp',date:'2040-03-01',type:'externalExpense',amount:700,category:'outside expense'},
 {id:'detail-ref',date:'2040-03-02',type:'refund',amount:100,category:'refund row',toAccountId:'cash-main'},
 {id:'detail-invest',date:'2040-03-03',type:'externalAssetIn',amount:900,category:'outside pension',toAccountId:state.integrated.accounts.find(a=>a.kind==='pension').id},
 {id:'detail-out',date:'2040-03-04',type:'externalWithdrawal',amount:800,category:'withdrawal row',fromAccountId:'cash-main'});
 globalThis.nodes={};document.querySelector=key=>nodes[key]||(nodes[key]={});openSheet=()=>{};openIntegratedMonthDetail('2040-03');`);
 const html=run(c,"nodes['#sheetBody'].innerHTML");
 for(const [name,value] of [['outside expense',700],['refund row',-100],['outside pension',900],['withdrawal row',800]])assert.ok(html.includes(`<span>${name}</span><strong>${value}원</strong>`),name);
});
test('inactive schedules retain completed historical occurrences without adding unpaid plans',()=>{
 const c=env();run(c,`state.financeSchedules.items.push({id:'history-insurance',name:'QA closed policy',kind:'insurance',active:false,day:25,startDate:'2031-01-01',endDate:'2034-03-31',amount:10000});state.integrated.ledger.push({id:'history-paid',date:'2034-02-25',type:'expense',amount:10000,fromAccountId:'cash-main',meta:{scheduleId:'history-insurance',scheduleDate:'2034-02-25'}})`);
 assert.equal(run(c,"scheduleOccurrences('2034-02').find(x=>x.schedule.id==='history-insurance').status"),'done');
 for(const month of ['2034-01','2034-03','2034-04','2060-12'])assert.equal(run(c,`scheduleOccurrences('${month}').some(x=>x.schedule.id==='history-insurance')`),false);
});

test('ISA dividend filter includes ETF distributions and linked detail shows reinvestment',()=>{
 const c=env();vm.runInContext(fs.readFileSync(path.join(root,'core-visual-utils.js'),'utf8'),c);vm.runInContext(fs.readFileSync(path.join(root,'isa-summary.js'),'utf8'),c);
 run(c,`globalThis.a=state.accounts[0];currentAccount=()=>a;setting().txFilter='dividend';a.transactions.push({id:'qa-dist',type:'distribution',date:'2033-02-01',holdingId:'qa-etf',amount:2000,linkedBuyId:'qa-buy'},{id:'qa-buy',type:'buy',date:'2033-02-02',holdingId:'qa-etf',qty:1,price:10000,sourceDividendId:'qa-dist'});a.holdings.push({id:'qa-etf',name:'QA ETF',qty:0,avgPrice:0,currentPrice:10000});`);
 assert.ok(run(c,'transactionsPage()').includes('data-tx="qa-dist"'));assert.ok(!run(c,'transactionsPage()').includes('data-tx="qa-buy"'));
 run(c,`globalThis.nodes={};document.querySelector=key=>nodes[key]||(nodes[key]={addEventListener:()=>{}});openSheet=()=>{};openTransactionDetail('qa-dist');`);
 assert.ok(run(c,"nodes['#sheetBody'].innerHTML").includes('연결된 매수'));assert.ok(run(c,"nodes['#sheetBody'].innerHTML").includes('2033.02.02 · 10,000원'));
});
test('ISA quick registration binds the button inside the action sheet',()=>{
 const c=env();run(c,`globalThis.quickButton={};globalThis.mainButton={};globalThis.grid={querySelector:key=>quickButton};document.querySelector=key=>key==='#actionGrid'?grid:key==='[data-register]'?mainButton:{};openSheet=()=>{};openTransactionChoice();`);
 assert.equal(run(c,'quickButton.onclick===openRegisterChoice'),true);assert.equal(run(c,'mainButton.onclick'),undefined);
});
