'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.join(__dirname,'..');
function env(){const storage=new Map(),c=vm.createContext({console,Date,Set,Map,URL,Blob,TextEncoder,TextDecoder,Uint8Array,DataView,ArrayBuffer,Intl,Math,JSON,Number,String,Boolean,Object,RegExp,Promise,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},document:{querySelector:()=>null,querySelectorAll:()=>[],documentElement:{dataset:{}},body:{dataset:{}}},window:{addEventListener:()=>{}},navigator:{},location:{search:'?qa=1',hash:''},setTimeout:()=>0,clearTimeout:()=>{}});for(const f of ['core-config.js','broker-kis.js','data-defaults.js','integrated-ledger-engine.js','integrated-schedule-engine.js','integrated-finance-engine.js','store-state.js','core-accessors.js','pension-contributions.js','pension-ledger.js','pension-assets.js','isa-validation.js','isa-ledger.js','isa-registration.js','isa-maturity-policy.js','integrated-forms.js','integrated-finance-ui.js','insurance.js','backup.js','export-csv.js','integrated-pages.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),c,{filename:f});const bytes=fs.readFileSync(path.join(root,'qa-evidence/manual-30-year-backup.zip')),offset=30+bytes.readUInt16LE(26)+bytes.readUInt16LE(28);c.fixture=JSON.parse(require('node:zlib').inflateRawSync(bytes.subarray(offset,offset+bytes.readUInt32LE(18))).toString()).data;vm.runInContext('state=normalizeState(fixture)',c);return c}
const run=(c,s)=>vm.runInContext(s,c);
test('30-year backup pension valuation equals integrated valuation without verification flag',()=>{const c=env();assert.equal(run(c,"pensionAssetMetrics('all').value"),108022400);assert.equal(run(c,'integratedFinancialModel().pension+integratedFinancialModel().irp'),108022400);assert.equal(run(c,'integratedFinancialModel().netAssets'),799612010)});
test('30-year linked contributions appear once in views and CSV without mutating ledger',()=>{const c=env(),before=run(c,'JSON.stringify(state)');assert.equal(run(c,"pensionVisibleTransactionRows().filter(t=>t.linkedContribution).length"),720);assert.equal(run(c,"excelCsvEntries().find(x=>x.name==='ISA거래.csv').text.split('\\r\\n').filter(Boolean).length"),37);assert.equal(run(c,"excelCsvEntries().find(x=>x.name==='연금거래.csv').text.split('\\r\\n').filter(Boolean).length"),733);assert.equal(run(c,'JSON.stringify(state)'),before)});
test('insurance actual payments use ledger only and retain separate historic declared totals',()=>{const c=env();c.p={id:'new',premium:10000,contractDate:'2031-01-01',paymentEndDate:'2060-12-31',status:'active'};assert.equal(run(c,'insurancePremiumSummary(p).paid'),0);run(c,"state.financeSchedules.items.push({id:'new-s',kind:'insurance',productId:'new'});state.integrated.ledger.push({id:'ip',type:'expense',date:'2034-02-01',amount:10000,fromAccountId:'cash-main',meta:{scheduleId:'new-s'}})");assert.equal(run(c,'insurancePremiumSummary(p).paid'),10000);c.p.status='ended';assert.equal(run(c,'insurancePremiumSummary(p).remaining'),0)});
test('partial and cross-month refunds restore cash, reduce refund-month spending and cap total',()=>{const c=env();run(c,"state.integrated.ledger.push({id:'purchase',type:'expense',date:'2060-10-01',amount:10000,fromAccountId:'cash-main',category:'QA 환불',fixed:false})");const cash=run(c,"integratedReplay().assets['cash-main']"),spend=run(c,"integratedSpendingAnalysis('2060-11').total");assert.equal(run(c,"recordIntegratedRefund('purchase','2060-11-02',3000).ok"),true);assert.equal(run(c,"recordIntegratedRefund('purchase','2060-12-02',7000).ok"),true);assert.equal(run(c,"recordIntegratedRefund('purchase','2060-12-03',1).ok"),false);assert.equal(run(c,"integratedReplay().assets['cash-main']"),cash+10000);assert.equal(run(c,"integratedSpendingAnalysis('2060-11').total"),spend-3000);assert.equal(run(c,"state.integrated.ledger.find(t=>t.id==='purchase').amount"),10000);run(c,"state.integrated.ledger=state.integrated.ledger.filter(t=>t.id!=='purchase')");assert.ok(run(c,"integratedIssues().some(x=>x.includes('환불 원거래'))"))});
test('ISA closure transfers once, keeps archive contributions and restores consistently',()=>{const c=env();c.id=run(c,'state.accounts[0].id');const before=run(c,'integratedFinancialModel().netAssets');assert.equal(run(c,"recordIsaLifecycle(id,{action:'close',date:'2033-12-31',settlement:10800000,tax:0}).ok"),true);assert.equal(run(c,'integratedFinancialModel().netAssets'),before);assert.equal(run(c,'centralIsaReplayRows(state.accounts[0],true).length'),36);assert.equal(run(c,"recordIsaLifecycle(id,{action:'close',date:'2033-12-31',settlement:10800000,tax:0}).ok"),false);run(c,'state=normalizeState(JSON.parse(JSON.stringify(state)))');assert.equal(run(c,'integratedFinancialModel().netAssets'),before)});
test('ISA extension keeps history and pension transfer preserves net assets',()=>{const c=env();c.id=run(c,'state.accounts[0].id');assert.equal(run(c,"recordIsaLifecycle(id,{action:'extend',date:'2033-12-31',maturityAt:'2036-12-31'}).ok"),true);const before=run(c,'integratedFinancialModel().netAssets');c.target=run(c,"pensionStore().accounts.find(a=>a.kind==='pension').id");const result=run(c,"recordIsaLifecycle(id,{action:'transfer',date:'2036-12-31',settlement:10800000,tax:0,transfer:10000000,targetAccountId:target})");assert.equal(result.ok,true,result.error);assert.equal(run(c,'integratedFinancialModel().netAssets'),before);assert.equal(run(c,"centralPensionContributionRows().filter(t=>t.type==='isaTransfer').length"),1)});

test('refund display stays positive in net spending rows',()=>{const c=env();assert.equal(run(c,"integratedTxAmountMarkup({type:'refund',amount:-1000}).includes('+-')"),false)});

function settlementEnv(){const c=env();c.sheetDirty=false;c.FormData=class{constructor(form){this.values=form.values}get(k){return this.values[k]??null}};run(c,"toast=s=>{globalThis.message=s};persist=()=>true;closeSheets=()=>{};render=()=>{};state.financialProducts.items.push({id:'settle-test',name:'QA 정산',type:'deposit',status:'active',startDate:'2031-01-01'});syncFinancialProductStructures(state);state.integrated.ledger.push({id:'settle-principal',type:'externalAssetIn',date:'2035-01-01',amount:1000000,toAccountId:'finance-asset-settle-test',productId:'settle-test'})");return c}
test('early cancellation keeps principal and loss balanced through 2060',()=>{const c=settlementEnv();const before=run(c,'integratedFinancialModel().netAssets');c.form={dataset:{productId:'settle-test'},values:{date:'2036-01-01',received:'950000',reason:'earlyCancel'}};run(c,'saveFinanceSettlement(form)');assert.equal(run(c,'integratedFinancialModel().netAssets'),before-50000);assert.equal(run(c,"financialProduct('settle-test').status"),'ended');assert.equal(run(c,"financeProductBalance(financialProduct('settle-test'))"),0);for(let year=2036;year<=2060;year++)assert.equal(run(c,`integratedReplay(integratedOperationalLedger().filter(t=>t.date<='${year}-12-31')).assets['finance-asset-settle-test']`),0);const count=run(c,'state.integrated.ledger.length');run(c,'saveFinanceSettlement(form)');assert.equal(run(c,'state.integrated.ledger.length'),count)});
test('settlement rejects invalid dates, amounts and later transactions without changes',()=>{for(const values of [{date:'2034-12-31',received:'900000'},{date:'2036-01-01',received:'NaN'},{date:'2036-01-01',received:'-1'},{date:'2036-01-01',received:''},{date:'2061-01-01',received:'900000'}]){const c=settlementEnv(),before=run(c,'JSON.stringify(state)');c.form={dataset:{productId:'settle-test'},values};run(c,'saveFinanceSettlement(form)');assert.equal(run(c,'JSON.stringify(state)'),before,JSON.stringify(values))}});
test('settlement validation failure cannot leave half a settlement',()=>{const c=settlementEnv(),before=run(c,'JSON.stringify(state)');run(c,"integratedValidateCandidate=t=>t.type==='expense'?'QA rejection':''");c.form={dataset:{productId:'settle-test'},values:{date:'2036-01-01',received:'900000'}};run(c,'saveFinanceSettlement(form)');assert.equal(run(c,'JSON.stringify(state)'),before)});

test('actual early repayment fee is an expense and never reduces principal twice',()=>{const c=settlementEnv();run(c,"state.financialProducts.items.push({id:'loan-fee',name:'QA 수수료',type:'loan',status:'active',startDate:'2031-01-01'});syncFinancialProductStructures(state);state.integrated.ledger.push({id:'fee-loan-open',date:'2035-01-01',type:'openingLiability',amount:1000000,liabilityId:'finance-debt-loan-fee'})");const before=run(c,'integratedFinancialModel().netAssets'),cash=run(c,"integratedReplay().assets['cash-main']");c.form={dataset:{productId:'loan-fee',action:'payoff'},values:{date:'2036-01-01',amount:'1000000',source:'tracked',repaymentFee:'10000'}};run(c,'saveFinanceMovement(form)');assert.equal(run(c,"financeProductBalance(financialProduct('loan-fee'))"),0);assert.equal(run(c,'integratedFinancialModel().netAssets'),before-10000);assert.equal(run(c,"integratedReplay().assets['cash-main']"),cash-1010000);assert.equal(run(c,"financialProduct('loan-fee').status"),'ended')});
