'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
const forms=fs.readFileSync(path.join(root,'pension-forms.js'),'utf8');
const pages=fs.readFileSync(path.join(root,'pension-pages.js'),'utf8');
const integratedCss=fs.readFileSync(path.join(root,'css-integrated.css'),'utf8');
const pwa=fs.readFileSync(path.join(root,'pwa.js'),'utf8');
const analysis=fs.readFileSync(path.join(root,'chart-asset-analysis.js'),'utf8');
const settings=fs.readFileSync(path.join(root,'ui-settings.js'),'utf8');
const initialImport=fs.readFileSync(path.join(root,'initial-import.js'),'utf8');
assert.match(forms,/pensionArchiveTransactionRows/);
assert.match(forms,/거래·과거 확정자료/);
assert.match(forms,/data-pension-archive-tx/);
assert.match(forms,/brokerKisVisibleOrders/);
assert.match(forms,/data-pension-kis-order/);
assert.match(forms,/한투 자동조회/);
assert.match(pages,/data-pension-kis-refresh/);
assert.match(pages,/if\(scope!==['"]all['"]\)return['"]{2}/);
assert.match(pages,/한투 연금 조회/);
assert.doesNotMatch(pages,/자동 갱신|10분 경과/);
assert.doesNotMatch(pages,/pension-asset-kpis single/);
assert.match(integratedCss,/\.spending-hero\{[^}]*border-radius:var\(--r2\)/);
assert.doesNotMatch(integratedCss,/\.spending-hero\{[^}]*var\(--radius\)/);
assert.match(pwa,/controllerchange/);
assert.match(pwa,/updateViaCache:'none'/);
assert.match(analysis,/확정수익 환산자산/);
assert.match(analysis,/basis\+x\.cumulativeTotal/);
assert.match(analysis,/당시 실제 계좌잔액이 아니라/);
assert.match(settings,/name="monthlyContribution"/);
assert.match(settings,/projection\.monthlyContribution=monthlyContribution/);
assert.match(initialImport,/add\.pensionProjection/);
assert.match(initialImport,/candidate\.pension\.projection/);
console.log('pension visible history UI tests: PASS');
