'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.join(__dirname,'..'),storage=new Map([['asset-os-v1.9.45-live','LIVE-SENTINEL']]);
const localStorage={get length(){return storage.size},key:i=>[...storage.keys()][i]??null,getItem:k=>storage.has(k)?storage.get(k):null,setItem:(k,v)=>storage.set(String(k),String(v)),removeItem:k=>storage.delete(String(k))};
let networkClients=0,fetches=0;
const document={querySelector:()=>null,querySelectorAll:()=>[],documentElement:{dataset:{},classList:{add(){},remove(){}},scrollHeight:0},body:{dataset:{}}};
const window={addEventListener(){},removeEventListener(){},scrollTo(){},isSecureContext:false,supabase:{createClient(){networkClients++;throw new Error('QA must not initialize Supabase')}}};
const context=vm.createContext({console,Date,Set,Map,URL,Blob,File:global.File,TextEncoder,TextDecoder,Uint8Array,DataView,ArrayBuffer,Intl,Math,JSON,Number,String,Boolean,Object,RegExp,Promise,encodeURIComponent,decodeURIComponent,localStorage,document,window,navigator:{},location:{search:'?qa=1',hash:'',pathname:'/asset-os/'},history:{replaceState(){}},fetch:async()=>{fetches++;throw new Error('QA network blocked')},requestAnimationFrame:fn=>fn(),setTimeout:()=>0,clearTimeout(){} });
const files=['core-config.js','broker-kis.js','broker-kis-client.js','data-defaults.js','integrated-ledger-engine.js','integrated-schedule-engine.js','integrated-finance-engine.js','store-migrations.js','store-state.js','core-accessors.js','pension-contributions.js','pension-ledger.js','pension-assets.js','isa-validation.js','isa-ledger.js','integrated-forms.js','qa-mode.js','supabase-sync.js'];
for(const file of files)vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),context,{filename:file});
const run=(code,args=[])=>vm.runInContext(code,Object.assign(context,{__args:args})),plain=x=>JSON.parse(JSON.stringify(x));
assert.equal(run('QA_MODE'),true);assert.equal(run('KEY'),'asset-os-qa-v1');assert.equal(run('localYmd()'),'2055-12-31');
run('state=qaBuildThirtyYearState();lastPersistedState=clone(state)');
assert.deepEqual(plain(run('qaDatasetStats()')),{isa:759,pension:780,integrated:4351,total:5890,totalAssets:1025410000,cash:215410000});
assert.deepEqual(plain(run('integratedIssues()')),[]);assert.deepEqual(plain(run('pensionTransactionIssues()')),[]);assert.deepEqual(plain(run('allIsaIssues()')),[]);assert.deepEqual(plain(run('brokerKisIssues(state.brokerKis)')),[]);
const mistakeCounts=plain(run('({integrated:state.integrated.ledger.length,pension:state.pension.transactions.length})'));
assert.match(run('integratedValidateCandidate({id:"bad-zero",date:"2055-12-30",type:"expense",amount:0,fromAccountId:"cash-main"})'),/1원 이상/);
assert.match(run('integratedValidateCandidate({id:"bad-same",date:"2055-12-30",type:"internalTransfer",amount:1000,fromAccountId:"cash-main",toAccountId:"cash-main"})'),/같은 계좌/);
assert.match(run('integratedValidateCandidate({id:"bad-over",date:"2055-12-30",type:"expense",amount:1e12,fromAccountId:"cash-main"})'),/잔액이 부족/);
assert.match(run('pensionTransactionSave({accountId:"qa-irp",holdingId:"qa-irp-h",type:"sell",date:"2055-12-30",qty:999999,price:100000,fee:0,tax:0}).error'),/초과매도/);
assert.deepEqual(plain(run('({integrated:state.integrated.ledger.length,pension:state.pension.transactions.length})')),mistakeCounts,'차단된 실수는 원장을 바꾸면 안 됨');
assert.equal(run('state.brokerKis.balanceSnapshots.length'),2);assert.equal(run('state.brokerKis.orders.length'),1);assert.equal(run('state.brokerKis.rights.length'),1);
assert.equal(run('persist(false)'),true);assert.equal(storage.get('asset-os-v1.9.45-live'),'LIVE-SENTINEL','운영 키는 절대 변경 금지');assert.ok(storage.get('asset-os-qa-v1').length>100000);
const before=plain(run('qaDatasetStats()'));run('state=loadState()');assert.deepEqual(plain(run('qaDatasetStats()')),before,'QA 새로고침 보존');
assert.equal(run('brokerKisClient.configure(BROKER_KIS_PUBLIC_CONFIG).ok'),true);assert.equal(networkClients,0);assert.equal(run('brokerKisClient.consumeRedirect().error'),'QA_NETWORK_BLOCKED');
(async()=>{assert.equal(await run('initSupabaseCloud()'),false);assert.equal(await run('cloudPushState()'),false);assert.equal(await run('cloudReconcileState()'),false);assert.equal(networkClients,0);assert.equal(fetches,0);console.log('QA mode isolation and 30-year dataset tests: PASS')})().catch(error=>{console.error(error);process.exitCode=1});
