'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8'),boot=fs.readFileSync(path.join(root,'boot.js'),'utf8'),worker=fs.readFileSync(path.join(root,'service-worker.js'),'utf8'),core=fs.readFileSync(path.join(root,'core-config.js'),'utf8'),cloud=fs.readFileSync(path.join(root,'supabase-sync.js'),'utf8'),manifest=JSON.parse(fs.readFileSync(path.join(root,'manifest.webmanifest'),'utf8'));
const home=fs.readFileSync(path.join(root,'home.js'),'utf8'),pensionPages=fs.readFileSync(path.join(root,'pension-pages.js'),'utf8');
assert.match(html,/<html[^>]+class="asset-auth-locked"/);
assert.ok(html.indexOf('id="assetAuthGate"')<html.indexOf('<div class="app">'));
assert.match(html,/\.asset-auth-locked \.app/);
assert.doesNotMatch(boot,/location\.hash='#\/home';render\(\);refreshCloudProfileUI\(\);initSupabaseCloud/);
assert.match(boot,/startAssetAuthenticatedApp\(\)/);
assert.match(html,/Asset OS v0\.4/);
const brokerProjectUrl=core.match(/projectUrl:'([^']+)'/)?.[1],cloudProjectUrl=cloud.match(/SUPABASE_URL='([^']+)'/)?.[1];
assert.equal(cloudProjectUrl,brokerProjectUrl,'Google cloud and KIS auth must use the configured Supabase project URL');
assert.match(cloud,/function cloudAuthCallbackFailure/);
assert.match(cloud,/OAuth Client Secret/);
assert.match(home,/납입·통합 원장 연결액 · 종목 미연결/);
assert.match(pensionPages,/한투 기타자산/);
assert.match(pensionPages,/주식·ETF·ETN만 종목 조회/);
assert.match(html,/pension-assets\.js\?v=0\.4\.1/);
assert.match(html,/home\.js\?v=0\.4\.1/);
const productionCorpus=fs.readdirSync(root).filter(name=>name.endsWith('.js')).map(name=>fs.readFileSync(path.join(root,name),'utf8')).join('\n');
for(const obsolete of ['verifyOtp','scheduleTargetText','stripInvestmentQaFixtures','applyRealFinanceBootstrap'])assert.doesNotMatch(productionCorpus,new RegExp(`\\b${obsolete}\\b`),`obsolete function remained: ${obsolete}`);
assert.equal(manifest.start_url,'./');
assert.equal(manifest.display,'standalone');
for(const icon of manifest.icons){const file=path.join(root,icon.src.replace(/^\.\//,''));assert.ok(fs.existsSync(file),`missing ${icon.src}`)}
for(const file of fs.readdirSync(root).filter(name=>/\.(?:js|css)$/.test(name)))assert.ok(worker.includes(`./${file}`),`service worker shell missing ${file}`);
console.log('v0.4 auth gate and PWA shell tests: PASS');
