'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8'),boot=fs.readFileSync(path.join(root,'boot.js'),'utf8'),worker=fs.readFileSync(path.join(root,'service-worker.js'),'utf8'),core=fs.readFileSync(path.join(root,'core-config.js'),'utf8'),cloud=fs.readFileSync(path.join(root,'supabase-sync.js'),'utf8'),manifest=JSON.parse(fs.readFileSync(path.join(root,'manifest.webmanifest'),'utf8'));
const home=fs.readFileSync(path.join(root,'home.js'),'utf8'),isaSummary=fs.readFileSync(path.join(root,'isa-summary.js'),'utf8'),pensionForms=fs.readFileSync(path.join(root,'pension-forms.js'),'utf8'),pensionPages=fs.readFileSync(path.join(root,'pension-pages.js'),'utf8'),integratedForms=fs.readFileSync(path.join(root,'integrated-forms.js'),'utf8'),integratedPages=fs.readFileSync(path.join(root,'integrated-pages.js'),'utf8'),storeState=fs.readFileSync(path.join(root,'store-state.js'),'utf8'),sharedCss=fs.readFileSync(path.join(root,'css-shared-common.css'),'utf8');
assert.match(html,/<html[^>]+class="asset-auth-locked"/);
assert.ok(html.indexOf('id="assetAuthGate"')<html.indexOf('<div class="app">'));
assert.match(html,/\.asset-auth-locked \.app/);
assert.doesNotMatch(boot,/location\.hash='#\/home';render\(\);refreshCloudProfileUI\(\);initSupabaseCloud/);
assert.match(boot,/startAssetAuthenticatedApp\(\)/);
assert.match(html,/Asset OS v0\.4/);
const brokerProjectUrl=core.match(/projectUrl:'([^']+)'/)?.[1],cloudProjectUrl=cloud.match(/SUPABASE_URL='([^']+)'/)?.[1];
assert.equal(cloudProjectUrl,brokerProjectUrl,'Google cloud and KIS auth must use the configured Supabase project URL');
assert.match(cloud,/function cloudAuthCallbackFailure/);
assert.match(cloud,/OAuth Client Secret/);
assert.match(home,/납입·통합 원장 연결액 · 종목 미연결/);
assert.match(pensionPages,/한투 기타자산/);
assert.match(pensionPages,/주식·ETF·ETN만 종목 조회/);
assert.match(html,/pension-assets\.js\?v=0\.4\.27/);
assert.match(html,/pension-forms\.js\?v=0\.4\.29/);
assert.match(html,/source-archive\.js\?v=0\.4\.9/);
assert.match(html,/css-integrated\.css\?v=0\.4\.10/);
assert.match(html,/css-pension\.css\?v=0\.4\.21/);
assert.match(html,/css-shared-common\.css\?v=0\.4\.12/);
assert.match(html,/isa-summary\.js\?v=0\.4\.28/);
assert.match(isaSummary,/year=localYmd\(\)\.slice\(0,4\)/,'ISA dividend year must follow the app date');
assert.doesNotMatch(isaSummary,/year=String\(new Date\(\)\.getFullYear\(\)\)/);
assert.match(html,/pension-pages\.js\?v=0\.4\.27/);
assert.match(html,/integrated-pages\.js\?v=0\.4\.29/);
assert.match(html,/integrated-forms\.js\?v=0\.4\.29/);
assert.match(html,/store-state\.js\?v=0\.4\.29/);
assert.match(integratedForms,/closeSheets\(\{all:true\}\)/,'saved integrated edits must not reopen a stale parent detail');
assert.match(storeState,/typeof qaRenderStats==='function'/,'QA banner must refresh after every successful persist');
assert.match(integratedPages,/등록 고정비 일정/);
assert.match(integratedPages,/실제 지출은 소비 탭에서 확인하세요/);
assert.match(pensionForms,/pensionStore\(\)\.holdings\.find\(x=>x\.id===t\.holdingId\)\|\|pensionHoldingById/,'transaction names must fall back to the local holding ledger');
assert.match(integratedPages,/month=integratedMonthBar\(\)/,'all integrated tabs must reserve the same month-control row');
assert.match(sharedCss,/\.integrated-overview-hero,[\s\S]*?\.spending-hero\{[^}]*height:177px/,'integrated overview and spending heroes must have the same outer height');
assert.match(html,/pwa\.js\?v=0\.4\.29/);
assert.match(html,/qa-mode\.js\?v=0\.4\.26/);
assert.match(html,/core-visual-utils\.js\?v=0\.4\.28/);
assert.match(html,/initial-import\.js\?v=0\.4\.9/);
assert.match(html,/chart-asset-analysis\.js\?v=0\.4\.17/);
assert.match(html,/ui-settings\.js\?v=0\.4\.22/);
assert.match(html,/home\.js\?v=0\.4\.22/);
assert.doesNotMatch(html,/data-profile-action="source-archive"/);
assert.doesNotMatch(html,/data-profile-action="install"/);
assert.doesNotMatch(html,/data-profile-action="accounts"/);
assert.match(html,/ai-strategy\.js\?v=0\.4\.23/);
assert.match(html,/data-profile-action="ai-strategy"/);
assert.doesNotMatch(pensionPages,/data-ai-strategy/);
const productionCorpus=fs.readdirSync(root).filter(name=>name.endsWith('.js')).map(name=>fs.readFileSync(path.join(root,name),'utf8')).join('\n');
for(const obsolete of ['verifyOtp','scheduleTargetText','stripInvestmentQaFixtures','applyRealFinanceBootstrap'])assert.doesNotMatch(productionCorpus,new RegExp(`\\b${obsolete}\\b`),`obsolete function remained: ${obsolete}`);
assert.equal(manifest.start_url,'./');
assert.equal(manifest.display,'standalone');
for(const icon of manifest.icons){const file=path.join(root,icon.src.replace(/^\.\//,''));assert.ok(fs.existsSync(file),`missing ${icon.src}`)}
for(const file of fs.readdirSync(root).filter(name=>/\.(?:js|css)$/.test(name)))assert.ok(worker.includes(`./${file}`),`service worker shell missing ${file}`);
console.log('v0.4 auth gate and PWA shell tests: PASS');
